const KEY='imds_school_manager_v4_3';
const defaultData={students:[],payments:[],grades:[],attendance:[],social:[],teachers:[],teacherPayments:[],expenses:[],exams:[],planning:[],admins:[],adminLogs:[],meta:{nextReceipt:1,nextTeacherReceipt:1}};
let data=loadData();
const departments={
'Ouest':['Port-au-Prince','Delmas','Pétion-Ville','Kenscoff','Carrefour','Gressier','Léogâne','Grand-Goâve','Petit-Goâve','Fonds-Verrettes','Cornillon','Thomazeau','Ganthier','Croix-des-Bouquets','Cité Soleil','Tabarre','Cabaret','Arcahaie','Anse-à-Galets','Pointe-à-Raquette'],
'Sud-Est':['Jacmel','Cayes-Jacmel','La Vallée-de-Jacmel','Marigot','Bainet','Côtes-de-Fer','Belle-Anse','Anse-à-Pitres','Thiotte','Grand-Gosier'],
'Nord':['Cap-Haïtien','Limonade','Quartier-Morin','Acul-du-Nord','Plaine-du-Nord','Milot','Grande-Rivière-du-Nord','Dondon','Saint-Raphaël','Pignon','La Victoire','Ranquitte','Borgne','Port-Margot','Limbé','Bas-Limbé','Plaisance','Pilate','Bahon'],
'Nord-Est':['Fort-Liberté','Ferrier','Perches','Ouanaminthe','Capotille','Mont-Organisé','Trou-du-Nord','Caracol','Sainte-Suzanne','Terrier-Rouge','Vallières','Carice','Mombin-Crochu'],
'Artibonite':['Gonaïves','Ennery','L’Estère','Gros-Morne','Terre-Neuve','Anse-Rouge','Saint-Marc','Verrettes','La Chapelle','Dessalines','Desdunes','Grande-Saline','Petite-Rivière-de-l’Artibonite','Marmelade','Saint-Michel-de-l’Attalaye','Liancourt','Montrouis'],
'Centre':['Hinche','Cerca-la-Source','Cerca-Carvajal','Maïssade','Thomonde','Thomassique','Mirebalais','Saut-d’Eau','Boucan-Carré','Lascahobas','Belladère','Savanette','Baptiste'],
'Sud':['Les Cayes','Torbeck','Chantal','Camp-Perrin','Maniche','Île-à-Vache','Port-Salut','Saint-Jean-du-Sud','Arniquet','Aquin','Saint-Louis-du-Sud','Cavaillon','Les Côteaux','Port-à-Piment','Roche-à-Bateau','Chardonnières','Les Anglais','Tiburon'],
'Grande-Anse':['Jérémie','Abricots','Bonbon','Chambellan','Moron','Marfranc','Anse-d’Hainault','Dame-Marie','Les Irois','Corail','Beaumont','Pestel','Roseaux'],
'Nord-Ouest':['Môle-Saint-Nicolas','Baie-de-Henne','Bombardopolis','Jean-Rabel','Port-de-Paix','Bassin-Bleu','Chansolme','La Tortue','La Pointe des Palmistes','Saint-Louis-du-Nord','Anse-à-Foleur'],
'Nippes':['Miragoâne','Petite-Rivière-de-Nippes','Fonds-des-Nègres','Paillant','Anse-à-Veau','Petit-Trou-de-Nippes','L’Asile','Arnaud','Baradères','Grand-Boucan','Plaisance-du-Sud']};
function loadData(){try{let d=JSON.parse(localStorage.getItem(KEY)||'null');if(!d){for(const k of ['imds_school_manager_v4_2','imds_school_manager_v4','imds_school_manager_v4_1','imds_school_manager_v3']){try{d=JSON.parse(localStorage.getItem(k)||'null')}catch{}if(d)break}}if(d&&d.students&&d.payments){const base=structuredClone(defaultData);const merged=Object.assign(base,d,{teachers:Array.isArray(d.teachers)?d.teachers:[],teacherPayments:Array.isArray(d.teacherPayments)?d.teacherPayments:[],expenses:Array.isArray(d.expenses)?d.expenses:[],exams:Array.isArray(d.exams)?d.exams:[],planning:Array.isArray(d.planning)?d.planning:[],admins:Array.isArray(d.admins)?d.admins:[],adminLogs:Array.isArray(d.adminLogs)?d.adminLogs:[],meta:Object.assign(base.meta,d.meta||{})});merged.grades=(Array.isArray(merged.grades)?merged.grades:[]).map(g=>({...g,year:g.year||'2026-2027',period:g.period||'1er contrôle',maxScore:Number(g.maxScore||100),value:Number(g.value||0)}));return merged}return structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function money(n){return new Intl.NumberFormat('fr-FR').format(Number(n)||0)+' HTG'}
function today(){return new Date().toLocaleDateString('fr-CA')}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function studentName(id){const s=data.students.find(x=>x.id===id);return s?s.fullName:'Élève supprimé'}
function paidFor(id){return data.payments.filter(p=>p.studentId===id).reduce((a,p)=>a+Number(p.amount||0),0)}
function dueFor(s){return Number(s.annualRequested||0)+Number(s.previousBalance||0)}
function tariffAmount(type){return Number({normal:normalPrice.value,bourse:scholarshipPrice.value,demi:halfScholarshipPrice.value,special:specialPrice.value}[type]||0)}
function teacherPay(t){return t.type==='heure'?Number(t.hourlyRate||0)*Number(t.hoursWorked||0):Number(t.fullTimeSalary||0)}
function currentMonth(){return new Date().toLocaleDateString('fr-CA').slice(0,7)}
function isoToday(){return new Date().toISOString().slice(0,10)}
function getTeacherName(id){const t=data.teachers.find(x=>x.id===id);return t?t.name:'Professeur supprimé'}
function teacherReceipt(t){return `IMDS-P-${String(t).padStart(6,'0')}`}

function showSection(id){document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.section===id));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showSection(b.dataset.section));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showSection(b.dataset.go));
function initDepartments(){birthDepartment.innerHTML='<option value="">Choisir le département</option>'+Object.keys(departments).map(d=>`<option>${esc(d)}</option>`).join('')}
birthDepartment.onchange=()=>{const list=departments[birthDepartment.value]||[];birthCommune.disabled=!list.length;birthCommune.innerHTML='<option value="">Choisir la commune</option>'+list.map(c=>`<option>${esc(c)}</option>`).join('')}
tariffType.onchange=()=>{annualRequested.value=tariffAmount(tariffType.value)};[normalPrice,scholarshipPrice,halfScholarshipPrice,specialPrice].forEach(x=>x.oninput=()=>{if(tariffType.value)annualRequested.value=tariffAmount(tariffType.value)});
studentPhoto.onchange=()=>{const f=studentPhoto.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas'),max=360,scale=Math.min(1,max/Math.max(im.width,im.height));c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);photoPreview.src=c.toDataURL('image/jpeg',.78);photoPreview.classList.remove('hidden')};im.src=r.result};r.readAsDataURL(f)};
teacherMonth.value=currentMonth();
function updateTeacherPayPreview(){const type=teacherType.value;const amount=type==='heure'?Number(teacherHourlyRate.value||0)*Number(teacherHoursWorked.value||0):Number(teacherFullTimeSalary.value||0);teacherPayPreview.textContent=money(amount)}
[teacherType,teacherHourlyRate,teacherHoursWorked,teacherFullTimeSalary].forEach(x=>x.oninput=x.onchange=updateTeacherPayPreview);
teacherType.onchange=()=>{updateTeacherPayPreview();teacherHourlyRate.closest('label').style.opacity=teacherType.value==='heure'?'1':'.55';teacherFullTimeSalary.closest('label').style.opacity=teacherType.value==='plein_temps'?'1':'.55'};

function renderStudents(){const q=studentSearch.value.toLowerCase();const rows=data.students.filter(s=>[s.fullName,s.nisu,s.class].join(' ').toLowerCase().includes(q)).map(s=>{const p=paidFor(s.id),d=dueFor(s);return `<tr><td>${s.photo?`<img class="avatar" src="${s.photo}" alt="">`:''}${esc(s.fullName)}</td><td>${esc(s.nisu||'—')}</td><td>${esc(s.class)}</td><td>${esc(s.tariffType||'—')}</td><td>${money(d)}</td><td>${money(p)}</td><td>${money(Math.max(0,d-p))}</td><td><span class="status ${s.status}">${esc(s.status)}</span></td><td><button class="btn mini" data-edit="${s.id}">Modifier</button> <button class="btn mini danger" data-delete="${s.id}">Supprimer</button></td></tr>`}).join('');studentsBody.innerHTML=rows||'<tr><td colspan="9">Aucun élève enregistré.</td></tr>';
document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cet élève et tout son historique ?')){const id=b.dataset.delete;data.students=data.students.filter(s=>s.id!==id);data.payments=data.payments.filter(p=>p.studentId!==id);data.grades=data.grades.filter(g=>g.studentId!==id);data.attendance=data.attendance.filter(a=>a.studentId!==id);save();toast('Élève supprimé')}});
document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editStudent(b.dataset.edit))}
function editStudent(id){const s=data.students.find(x=>x.id===id);if(!s)return;Object.entries({nisu:s.nisu,lastName:s.lastName,firstName:s.firstName,birthDate:s.birthDate,sex:s.sex,birthPlace:s.birthPlace,address:s.address,motherName:s.motherName,fatherName:s.fatherName,guardianName:s.guardianName,guardianPhone:s.guardianPhone,guardianCIN:s.guardianCIN,referredBy:s.referredBy,normalPrice:s.normalPrice,scholarshipPrice:s.scholarshipPrice,halfScholarshipPrice:s.halfScholarshipPrice,specialPrice:s.specialPrice,tariffType:s.tariffType,annualRequested:s.annualRequested,previousBalance:s.previousBalance,studentStatus:s.status}).forEach(([id,v])=>{if(document.getElementById(id))document.getElementById(id).value=v??''});studentClass.value=s.class;birthDepartment.value=s.birthDepartment||'';birthDepartment.onchange();birthCommune.value=s.birthCommune||'';photoPreview.src=s.photo||'';photoPreview.classList.toggle('hidden',!s.photo);studentForm.dataset.edit=id;showSection('students');window.scrollTo({top:0,behavior:'smooth'});toast('Mode modification activé')}
function fillSelects(){const o=data.students.map(s=>`<option value="${s.id}">${esc(s.fullName)} — ${esc(s.class)}</option>`).join('')||'<option value="">Aucun élève</option>';['paymentStudent','gradeStudent','attendanceStudent','bulletinStudent'].forEach(id=>document.getElementById(id).innerHTML=o);receiptSelect.innerHTML=data.payments.slice().reverse().map(p=>`<option value="${p.id}">${esc(p.receiptNumber)} — ${esc(studentName(p.studentId))} — ${money(p.amount)}</option>`).join('')||'<option value="">Aucun paiement</option>'}
function renderPayments(){paymentsBody.innerHTML=data.payments.slice().reverse().map(p=>`<tr><td>${p.date}</td><td>${esc(p.receiptNumber)}</td><td>${esc(studentName(p.studentId))}</td><td>${esc(p.reason)}</td><td>${esc(p.mode)}</td><td>${money(p.amount)}</td><td><button class="btn mini" data-receipt="${p.id}">Reçu</button></td></tr>`).join('')||'<tr><td colspan="7">Aucun paiement.</td></tr>';document.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>{showSection('receipts');receiptSelect.value=b.dataset.receipt;renderReceiptPreview()})}
function renderFinance(){let due=0,paid=0,up=0,late=0;const rows=data.students.map(s=>{const d=dueFor(s),p=paidFor(s),bal=Math.max(0,d-p);due+=d;paid+=p;if(bal<=0)up++;else late++;return `<tr><td>${esc(s.fullName)}</td><td>${money(s.annualRequested)}</td><td>${money(s.previousBalance)}</td><td>${money(d)}</td><td>${money(p)}</td><td>${money(bal)}</td><td>${bal<=0?'À jour':'En retard'}</td></tr>`}).join('');financeBody.innerHTML=rows||'<tr><td colspan="7">Aucun élève.</td></tr>';financeDue.textContent=money(due);financePaid.textContent=money(paid);financeBalance.textContent=money(Math.max(0,due-paid));financeUp.textContent=up;financeLate.textContent=late;statStudents.textContent=data.students.length;statAnnual.textContent=money(paid);statBalance.textContent=money(Math.max(0,due-paid));statUpToDate.textContent=up;statLate.textContent=late;const ym=today().slice(0,7);statToday.textContent=money(data.payments.filter(p=>p.date===today()).reduce((a,p)=>a+Number(p.amount),0));statMonth.textContent=money(data.payments.filter(p=>p.date.startsWith(ym)).reduce((a,p)=>a+Number(p.amount),0))}
function renderGrades(){const cls=bulletinClassFilter.value||'',per=bulletinPeriodFilter.value||'';const rows=data.grades.slice().reverse().filter(g=>{const st=data.students.find(s=>s.id===g.studentId);return (!cls||st?.class===cls)&&(!per||g.period===per)});gradesBody.innerHTML=rows.map(g=>{const st=data.students.find(s=>s.id===g.studentId);const eq=Number(g.maxScore)?Number(g.value||0)/Number(g.maxScore)*10:0;return `<tr><td>${esc(studentName(g.studentId))}</td><td>${esc(st?.class||'—')}</td><td>${esc(g.period||'1er contrôle')}</td><td>${esc(g.subject)}</td><td>${Number(g.value||0).toFixed(2)}</td><td>${Number(g.maxScore||100).toFixed(2)}</td><td>${eq.toFixed(2)}/10</td><td><button class="btn mini danger" data-delete-grade="${g.id}">Supprimer</button></td></tr>`}).join('')||'<tr><td colspan="8">Aucune note pour les critères choisis.</td></tr>';document.querySelectorAll('[data-delete-grade]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cette note ?')){data.grades=data.grades.filter(g=>g.id!==b.dataset.deleteGrade);save();toast('Note supprimée')}})}
function renderAttendance(){attendanceBody.innerHTML=data.attendance.slice().reverse().slice(0,100).map(a=>`<tr><td>${a.date}</td><td>${esc(studentName(a.studentId))}</td><td>${esc(a.status)}</td></tr>`).join('')||'<tr><td colspan="3">Aucune présence.</td></tr>';statAttendance.textContent=data.attendance.filter(a=>a.date===today()).length}
function renderSocial(){socialFeed.innerHTML=data.social.slice().reverse().map(p=>`<div class="social-post panel"><div><strong>${esc(p.author)}</strong><span>${p.date}</span></div><p>${esc(p.message)}</p></div>`).join('')||'<div class="panel">Aucune publication.</div>'}
function receiptHtml(p){const s=data.students.find(x=>x.id===p.studentId);return `<div class="receipt"><div class="receipt-head"><div><h2>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h2><p>REÇU DE PAIEMENT</p></div><strong>${esc(p.receiptNumber)}</strong></div><hr><p><b>Élève :</b> ${esc(s?.fullName||'')}</p><p><b>NISU :</b> ${esc(s?.nisu||'—')} &nbsp; <b>Classe :</b> ${esc(s?.class||'')}</p><p><b>Date :</b> ${p.date}</p><p><b>Motif :</b> ${esc(p.reason)}</p><p><b>Mode :</b> ${esc(p.mode)}</p><div class="amount-box">Montant payé : <strong>${money(p.amount)}</strong></div><p class="small">Merci pour votre paiement.</p><div class="signatures"><span>Signature responsable</span><span>Cachet / Signature IMDS</span></div></div>`}
function renderReceiptPreview(){const p=data.payments.find(x=>x.id===receiptSelect.value);receiptPreview.innerHTML=p?receiptHtml(p):'<p>Aucun paiement sélectionné.</p>'}
studentForm.onsubmit=e=>{e.preventDefault();const id=studentForm.dataset.edit||uid();const photo=photoPreview.src&&!photoPreview.classList.contains('hidden')?photoPreview.src:'';const obj={id,nisu:nisu.value.trim(),lastName:lastName.value.trim(),firstName:firstName.value.trim(),fullName:(lastName.value.trim()+' '+firstName.value.trim()).trim(),class:studentClass.value,birthDate:birthDate.value,sex:sex.value,birthPlace:birthPlace.value.trim(),birthDepartment:birthDepartment.value,birthCommune:birthCommune.value,address:address.value.trim(),motherName:motherName.value.trim(),fatherName:fatherName.value.trim(),guardianName:guardianName.value.trim(),guardianPhone:guardianPhone.value.trim(),guardianCIN:guardianCIN.value.trim(),referredBy:referredBy.value.trim(),normalPrice:Number(normalPrice.value)||0,scholarshipPrice:Number(scholarshipPrice.value)||0,halfScholarshipPrice:Number(halfScholarshipPrice.value)||0,specialPrice:Number(specialPrice.value)||0,tariffType:tariffType.value,annualRequested:Number(annualRequested.value)||0,previousBalance:Number(previousBalance.value)||0,status:studentStatus.value,photo:photo||(data.students.find(s=>s.id===id)?.photo||'')};const i=data.students.findIndex(s=>s.id===id);if(i>=0)data.students[i]=obj;else data.students.push(obj);delete studentForm.dataset.edit;studentForm.reset();annualRequested.value=0;photoPreview.src='';photoPreview.classList.add('hidden');save();toast(i>=0?'Dossier modifié':'Élève enregistré')};
resetStudentBtn.onclick=()=>{delete studentForm.dataset.edit;setTimeout(()=>{photoPreview.src='';photoPreview.classList.add('hidden')},0)};
studentSearch.oninput=renderStudents;
paymentForm.onsubmit=e=>{e.preventDefault();const sid=paymentStudent.value;if(!sid)return toast('Ajoutez d’abord un élève');const rn=receiptNumber.value.trim()||`IMDS-${String(data.meta.nextReceipt++).padStart(6,'0')}`;data.payments.push({id:uid(),studentId:sid,amount:Number(paymentAmount.value),reason:paymentReason.value,mode:paymentMode.value,receiptNumber:rn,note:paymentNote.value.trim(),date:today()});paymentForm.reset();save();toast('Paiement enregistré — reçu '+rn);showSection('receipts');receiptSelect.value=data.payments[data.payments.length-1].id;renderReceiptPreview()};
gradeForm.onsubmit=e=>{e.preventDefault();const value=Number(gradeValue.value),max=Number(gradeMax.value);if(max<=0||value<0||value>max)return toast('La note doit être comprise entre 0 et le barème choisi.');const rec={id:uid(),studentId:gradeStudent.value,subject:gradeSubject.value.trim(),value,maxScore:max,year:gradeYear.value.trim(),period:gradePeriod.value,date:today()};const existing=data.grades.find(g=>g.studentId===rec.studentId&&g.subject.toLowerCase()===rec.subject.toLowerCase()&&g.year===rec.year&&g.period===rec.period);if(existing){Object.assign(existing,rec,{id:existing.id});toast('Note mise à jour')}else{data.grades.push(rec);toast('Note enregistrée')}save();e.target.reset();gradeYear.value=bulletinYear.value||'2026-2027';gradeMax.value=100};attendanceForm.onsubmit=e=>{e.preventDefault();data.attendance.push({id:uid(),studentId:attendanceStudent.value,status:attendanceStatus.value,date:today()});save();toast('Présence enregistrée')};
socialForm.onsubmit=e=>{e.preventDefault();data.social.push({id:uid(),author:socialAuthor.value.trim(),message:socialMessage.value.trim(),date:new Date().toLocaleString('fr-FR')});e.target.reset();save();toast('Publication ajoutée')};
receiptSelect.onchange=renderReceiptPreview;previewReceiptBtn.onclick=renderReceiptPreview;printReceiptBtn.onclick=()=>{const p=data.payments.find(x=>x.id===receiptSelect.value);if(!p)return;const w=window.open('','_blank','width=800,height=900');w.document.write(`<html><head><title>${esc(p.receiptNumber)}</title><style>body{font-family:Arial;padding:30px}.receipt{max-width:680px;margin:auto;border:2px solid #176b52;padding:28px}.receipt-head{display:flex;justify-content:space-between;gap:20px}.receipt-head h2{font-size:20px}.amount-box{margin:25px 0;padding:18px;background:#f1f6f3;font-size:20px}.signatures{display:flex;justify-content:space-between;margin-top:70px}.small{color:#666}</style></head><body>${receiptHtml(p)}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()};
expenseDate.value=isoToday();expenseForm.onsubmit=e=>{e.preventDefault();const amount=Number(expenseAmount.value)||0;if(amount<=0)return toast('Entrez un montant valide');data.expenses.push({id:uid(),date:expenseDate.value||isoToday(),category:expenseCategory.value,description:expenseDescription.value.trim(),beneficiary:expenseBeneficiary.value.trim(),amount,mode:expenseMode.value,reference:expenseReference.value.trim(),note:expenseNote.value.trim()});save();toast('Dépense enregistrée');e.target.reset();expenseDate.value=isoToday()};expenseSearch.oninput=renderExpenses;

teacherForm.onsubmit=e=>{e.preventDefault();const obj={id:uid(),name:teacherName.value.trim(),sex:teacherSex.value,class:teacherClass.value.trim(),subjects:teacherSubjects.value.trim(),type:teacherType.value,hourlyRate:Number(teacherHourlyRate.value)||0,fullTimeSalary:Number(teacherFullTimeSalary.value)||0,hoursWorked:Number(teacherHoursWorked.value)||0,hoursAbsent:Number(teacherHoursAbsent.value)||0,daysAbsent:Number(teacherDaysAbsent.value)||0,dress:teacherDress.value,month:teacherMonth.value||currentMonth()};data.teachers.push(obj);save();toast('Professeur enregistré');e.target.reset();teacherMonth.value=currentMonth();teacherType.onchange()};
teacherSearch.oninput=renderTeachers;reportMonth.value=currentMonth();reportMonth.onchange=renderMonthlyReport;printMonthlyReport.onclick=printMonthly;
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`IMDS-sauvegarde-${today()}.json`;a.click();URL.revokeObjectURL(a.href);securityMessage.textContent='Sauvegarde exportée.'};
importFile.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.students||!x.payments)throw Error();data=Object.assign(structuredClone(defaultData),x);save();toast('Sauvegarde importée')}catch{alert('Fichier de sauvegarde invalide.')}};r.readAsText(f)};
clearBtn.onclick=()=>{if(confirm('ATTENTION : effacer toutes les données locales de l’IMDS sur cet appareil ?')){data=structuredClone(defaultData);save();toast('Données effacées')}};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden')});installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add('hidden')}};

function renderTeachers(){const q=(teacherSearch.value||'').toLowerCase();teachersBody.innerHTML=data.teachers.filter(t=>[t.name,t.sex,t.class,t.subjects].join(' ').toLowerCase().includes(q)).map(t=>{const pay=teacherPay(t);return `<tr><td>${esc(t.name)}</td><td>${esc(t.sex||'—')}</td><td>${esc(t.class||'—')}</td><td>${esc(t.subjects||'—')}</td><td>${t.type==='heure'?'Heure fournie':'Plein temps'}</td><td>${t.type==='heure'?Number(t.hoursWorked||0):'—'}</td><td>${Number(t.hoursAbsent||0)} h / ${Number(t.daysAbsent||0)} j</td><td>${esc(t.dress||'—')}</td><td>${money(pay)}</td><td><button class="btn mini" data-pay-teacher="${t.id}">Payer le mois</button> <button class="btn mini danger" data-delete-teacher="${t.id}">Supprimer</button></td></tr>`}).join('')||'<tr><td colspan="10">Aucun professeur enregistré.</td></tr>';
document.querySelectorAll('[data-delete-teacher]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer ce professeur et son historique de paiements ?')){const id=b.dataset.deleteTeacher;data.teachers=data.teachers.filter(t=>t.id!==id);data.teacherPayments=data.teacherPayments.filter(p=>p.teacherId!==id);save();toast('Professeur supprimé')}});
document.querySelectorAll('[data-pay-teacher]').forEach(b=>b.onclick=()=>payTeacher(b.dataset.payTeacher));
teacherPaymentsBody.innerHTML=data.teacherPayments.slice().reverse().map(p=>`<tr><td>${esc(p.month)}</td><td>${esc(getTeacherName(p.teacherId))}</td><td>${p.type==='heure'?'Heure fournie':'Plein temps'}</td><td>${money(p.amount)}</td><td>${p.paidDate}</td><td>${esc(p.receiptNumber)}</td><td><button class="btn mini" data-print-tpay="${p.id}">Imprimer</button></td></tr>`).join('')||'<tr><td colspan="7">Aucun paiement de professeur.</td></tr>';
document.querySelectorAll('[data-print-tpay]').forEach(b=>b.onclick=()=>printTeacherReceipt(b.dataset.printTpay))}
function payTeacher(id){const t=data.teachers.find(x=>x.id===id);if(!t)return;const month=teacherMonth.value||currentMonth();const already=data.teacherPayments.some(p=>p.teacherId===id&&p.month===month);if(already&&!confirm('Ce professeur a déjà un paiement enregistré pour ce mois. Ajouter un autre paiement ?'))return;const amount=teacherPay(t);if(amount<=0)return toast('Le montant calculé est de 0 HTG. Vérifiez les données du professeur.');const rn=teacherReceipt(data.meta.nextTeacherReceipt++);data.teacherPayments.push({id:uid(),teacherId:id,month,type:t.type,amount,paidDate:today(),receiptNumber:rn,hoursWorked:t.hoursWorked,hoursAbsent:t.hoursAbsent,daysAbsent:t.daysAbsent,dress:t.dress});save();toast('Paiement professeur enregistré — '+rn)}
function printTeacherReceipt(id){const p=data.teacherPayments.find(x=>x.id===id);if(!p)return;const w=window.open('','_blank','width=800,height=900');w.document.write(`<html><head><title>${esc(p.receiptNumber)}</title><style>body{font-family:Arial;padding:30px}.receipt{max-width:680px;margin:auto;border:2px solid #176b52;padding:28px}.head{display:flex;justify-content:space-between}.box{margin:25px 0;padding:18px;background:#f1f6f3;font-size:20px}.sign{display:flex;justify-content:space-between;margin-top:70px}</style></head><body><div class="receipt"><div class="head"><div><h2>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h2><p>REÇU DE PAIEMENT DU PROFESSEUR</p></div><strong>${esc(p.receiptNumber)}</strong></div><hr><p><b>Professeur :</b> ${esc(getTeacherName(p.teacherId))}</p><p><b>Mois :</b> ${esc(p.month)}</p><p><b>Type :</b> ${p.type==='heure'?'Heure fournie':'Plein temps'}</p><p><b>Heures travaillées :</b> ${p.hoursWorked||0}</p><p><b>Absences :</b> ${p.hoursAbsent||0} h / ${p.daysAbsent||0} j</p><p><b>Tenue :</b> ${esc(p.dress||'—')}</p><div class="box">Montant payé : <strong>${money(p.amount)}</strong></div><div class="sign"><span>Signature professeur</span><span>Signature IMDS</span></div></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function renderExpenses(){const q=(expenseSearch.value||'').toLowerCase();expensesBody.innerHTML=data.expenses.slice().reverse().filter(x=>[x.category,x.description,x.beneficiary,x.mode,x.reference].join(' ').toLowerCase().includes(q)).map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.category)}</td><td>${esc(x.description)}</td><td>${esc(x.beneficiary||'—')}</td><td>${esc(x.mode)}</td><td>${money(x.amount)}</td><td><button class="btn mini danger" data-delete-expense="${x.id}">Supprimer</button></td></tr>`).join('')||'<tr><td colspan="7">Aucune dépense enregistrée.</td></tr>';document.querySelectorAll('[data-delete-expense]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cette dépense ?')){data.expenses=data.expenses.filter(x=>x.id!==b.dataset.deleteExpense);save();toast('Dépense supprimée')}})}
function monthExpenses(month){return data.expenses.filter(x=>String(x.date||'').startsWith(month))}

function renderMonthlyReport(){const month=reportMonth.value||currentMonth();const pays=data.payments.filter(p=>p.date.startsWith(month));const tp=data.teacherPayments.filter(p=>p.month===month);const ex=monthExpenses(month);const revenue=pays.reduce((a,p)=>a+Number(p.amount||0),0),payroll=tp.reduce((a,p)=>a+Number(p.amount||0),0),expensesTotal=ex.reduce((a,p)=>a+Number(p.amount||0),0);reportStudentRevenue.textContent=money(revenue);reportTeacherPayroll.textContent=money(payroll);reportExpenses.textContent=money(expensesTotal);reportNet.textContent=money(revenue-payroll-expensesTotal);reportPaymentCount.textContent=pays.length;const modes={};pays.forEach(p=>{modes[p.mode]??={count:0,total:0};modes[p.mode].count++;modes[p.mode].total+=Number(p.amount||0)});reportModesBody.innerHTML=Object.entries(modes).map(([m,v])=>`<tr><td>${esc(m)}</td><td>${v.count}</td><td>${money(v.total)}</td></tr>`).join('')||'<tr><td colspan="3">Aucune recette.</td></tr>';reportPaymentsBody.innerHTML=pays.map(p=>`<tr><td>${p.date}</td><td>${esc(p.receiptNumber)}</td><td>${esc(studentName(p.studentId))}</td><td>${esc(p.reason)}</td><td>${esc(p.mode)}</td><td>${money(p.amount)}</td></tr>`).join('')||'<tr><td colspan="6">Aucune recette.</td></tr>';reportExpensesBody.innerHTML=ex.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.category)}</td><td>${esc(x.description)}</td><td>${esc(x.beneficiary||'—')}</td><td>${esc(x.mode)}</td><td>${money(x.amount)}</td></tr>`).join('')||'<tr><td colspan="6">Aucune dépense.</td></tr>';reportTeachersBody.innerHTML=tp.map(p=>`<tr><td>${esc(getTeacherName(p.teacherId))}</td><td>${esc(p.month)}</td><td>${p.type==='heure'?'Heure fournie':'Plein temps'}</td><td>${money(p.amount)}</td><td>${p.paidDate}</td><td>${esc(p.receiptNumber)}</td></tr>`).join('')||'<tr><td colspan="6">Aucun paiement professeur.</td></tr>'}
function printMonthly(){const month=reportMonth.value||currentMonth();renderMonthlyReport();const w=window.open('','_blank','width=900,height=1000');if(!w)return;w.document.write(`<html><head><title>Rapport financier ${month}</title><style>body{font-family:Arial;padding:25px}.head{text-align:center;border-bottom:2px solid #176b52;padding-bottom:12px}.cards{display:flex;gap:10px;margin:18px 0}.card{flex:1;border:1px solid #ddd;padding:12px}.card b{display:block;font-size:18px;margin-top:5px}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #ddd;padding:7px;text-align:left}th{background:#f1f5f3}.section{margin-top:25px}.sign{display:flex;justify-content:space-between;margin-top:60px}</style></head><body><div class="head"><h1>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h1><h2>RAPPORT FINANCIER MENSUEL</h2><p>Mois : ${month}</p></div><div class="cards"><div class="card">Recettes élèves<b>${reportStudentRevenue.textContent}</b></div><div class="card">Paiements professeurs<b>${reportTeacherPayroll.textContent}</b></div><div class="card">Dépenses<b>${reportExpenses.textContent}</b></div><div class="card">Solde mensuel<b>${reportNet.textContent}</b></div></div><div class="section"><h3>Recettes par mode</h3>${reportModesBody.parentElement.outerHTML}</div><div class="section"><h3>Détail des recettes</h3>${reportPaymentsBody.parentElement.outerHTML}</div><div class="section"><h3>Détail des dépenses</h3>${reportExpensesBody.parentElement.outerHTML}</div><div class="section"><h3>Paiements des professeurs</h3>${reportTeachersBody.parentElement.outerHTML}</div><div class="sign"><span>Préparé par : __________________</span><span>Direction : __________________</span></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function gradesForStudent(studentId,year,period){return data.grades.filter(g=>g.studentId===studentId&&(g.year||'2026-2027')===year&&(g.period||'1er contrôle')===period)}
function bulletinData(studentId,year,period){const s=data.students.find(x=>x.id===studentId);if(!s)return null;const gs=gradesForStudent(studentId,year,period);const total=gs.reduce((a,g)=>a+Number(g.value||0),0),possible=gs.reduce((a,g)=>a+Number(g.maxScore||100),0),avg=possible?total/possible*10:0;const classStudents=data.students.filter(x=>x.class===s.class&&x.status!=='transféré'&&x.status!=='abandonné');const averages=classStudents.map(x=>{const r=gradesForStudent(x.id,year,period);const t=r.reduce((a,g)=>a+Number(g.value||0),0),p=r.reduce((a,g)=>a+Number(g.maxScore||100),0);return {id:x.id,avg:p?t/p*10:0}}).filter(x=>x.avg>0).sort((a,b)=>b.avg-a.avg);const rank=averages.findIndex(x=>x.id===s.id)+1;return {s,gs,total,possible,avg,rank:rank||null,classSize:classStudents.length,year,period}}
function bulletinHTML(b){const s=b.s;const rows=b.gs.map(g=>{const eq=Number(g.maxScore)?Number(g.value||0)/Number(g.maxScore)*10:0;return `<tr><td>${esc(g.subject)}</td><td class="num">${Number(g.value||0).toFixed(2)}</td><td class="num">${Number(g.maxScore||100).toFixed(2)}</td><td class="num">${eq.toFixed(2)}</td></tr>`}).join('')||'<tr><td colspan="4" class="empty">Aucune note enregistrée pour cette période.</td></tr>';return `<article class="bulletin-page"><header class="bulletin-header"><div><h1>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h1><p>Éducation pour l'avenir</p></div><div class="bulletin-title">BULLETIN SCOLAIRE</div></header><div class="bulletin-meta"><div><b>Année scolaire :</b> ${esc(b.year)}</div><div><b>Période :</b> ${esc(b.period)}</div></div><section class="student-card"><div><p><b>Nom :</b> ${esc(s.lastName||'')}</p><p><b>Prénom :</b> ${esc(s.firstName||'')}</p><p><b>NISU :</b> ${esc(s.nisu||'')}</p></div><div><p><b>Classe :</b> ${esc(s.class||'')}</p><p><b>Sexe :</b> ${esc(s.sex||'')}</p><p><b>Date de naissance :</b> ${esc(s.birthDate||'')}</p></div></section><table class="bulletin-table"><thead><tr><th>Matière</th><th>Points obtenus</th><th>Points possibles</th><th>Équivalent /10</th></tr></thead><tbody>${rows}</tbody><tfoot><tr><th>TOTAL</th><th>${b.total.toFixed(2)}</th><th>${b.possible.toFixed(2)}</th><th>${b.avg.toFixed(2)} / 10</th></tr></tfoot></table><section class="bulletin-summary"><div><b>Moyenne générale</b><strong>${b.avg.toFixed(2)} / 10</strong></div><div><b>Rang</b><strong>${b.rank?b.rank+' / '+b.classSize:'—'}</strong></div><div><b>Décision</b><strong>________________</strong></div></section><section class="remarks"><b>Appréciation / Observation générale :</b><div></div></section><footer class="bulletin-signatures"><div>Professeur / Titulaire<br><span>________________________</span></div><div>Direction<br><span>________________________</span></div><div>Signature du parent<br><span>________________________</span></div></footer><div class="bulletin-foot">Document généré par IMDS School Manager • ${today()}</div></article>`}
function renderBulletinPreview(){const id=bulletinStudent.value,year=bulletinYear.value.trim(),period=bulletinPeriod.value;if(!id){bulletinPreview.innerHTML='<p class="small">Sélectionnez un élève pour afficher son bulletin.</p>';return}const b=bulletinData(id,year,period);bulletinPreview.innerHTML=b?bulletinHTML(b):''}
function printOneBulletin(id){const b=bulletinData(id,bulletinYear.value.trim(),bulletinPeriod.value);if(!b)return toast('Impossible de générer le bulletin.');const w=window.open('','_blank','width=900,height=1000');if(!w)return toast('Autorisez les fenêtres contextuelles pour imprimer.');w.document.write(`<html><head><title>Bulletin - ${esc(b.s.fullName||'élève')}</title><style>${bulletinPrintCSS()}</style></head><body>${bulletinHTML(b)}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function printClassBulletins(){const cls=bulletinClassFilter.value;if(!cls)return toast('Choisissez une classe pour générer les bulletins.');const year=bulletinYear.value.trim(),period=bulletinPeriod.value,students=data.students.filter(s=>s.class===cls&&s.status!=='transféré'&&s.status!=='abandonné');if(!students.length)return toast('Aucun élève dans cette classe.');const pages=students.map(s=>bulletinHTML(bulletinData(s.id,year,period))).join('');const w=window.open('','_blank','width=900,height=1000');if(!w)return toast('Autorisez les fenêtres contextuelles pour imprimer.');w.document.write(`<html><head><title>Bulletins ${esc(cls)} - ${esc(year)}</title><style>${bulletinPrintCSS()}</style></head><body>${pages}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function bulletinPrintCSS(){return `.bulletin-page{width:190mm;min-height:267mm;margin:0 auto;padding:10mm;box-sizing:border-box;font-family:Arial,sans-serif;color:#1d2b26;background:#fff;page-break-after:always}.bulletin-header{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #176b52;padding-bottom:10px}.bulletin-header h1{font-size:21px;margin:0}.bulletin-header p{margin:4px 0;font-size:12px}.bulletin-title{font-size:18px;font-weight:800}.bulletin-meta{display:flex;justify-content:space-between;margin:12px 0;padding:8px;background:#f1f6f3}.student-card{display:grid;grid-template-columns:1fr 1fr;border:1px solid #b9c8c1;padding:8px;margin-bottom:14px}.student-card p{margin:5px 0}.bulletin-table{width:100%;border-collapse:collapse}.bulletin-table th,.bulletin-table td{border:1px solid #aebbb5;padding:7px}.bulletin-table th{background:#e8f1ed}.num{text-align:center}.empty{text-align:center;padding:18px}.bulletin-summary{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-top:15px}.bulletin-summary div{border:1px solid #b9c8c1;padding:10px;text-align:center}.bulletin-summary strong{display:block;font-size:18px;margin-top:5px}.remarks{margin-top:15px;border:1px solid #b9c8c1;padding:10px}.remarks div{height:45px}.bulletin-signatures{display:grid;grid-template-columns:1fr 1fr 1fr;gap:15px;margin-top:35px;text-align:center}.bulletin-signatures span{display:inline-block;margin-top:22px}.bulletin-foot{text-align:center;margin-top:18px;font-size:9px;color:#68766f}@media print{@page{size:A4;margin:0}.bulletin-page{margin:0;box-shadow:none}}`}
function renderClassList(){const cls=classListSelect.value,year=classListYear.value.trim(),students=data.students.filter(s=>s.class===cls&&s.status!=='transféré'&&s.status!=='abandonné');const boys=students.filter(s=>s.sex==='Masculin').length,girls=students.filter(s=>s.sex==='Féminin').length;classListPreview.innerHTML=`<div class="panel"><h2>IMDS — Liste de formation : ${esc(cls)}</h2><p><b>Année scolaire :</b> ${esc(year)} &nbsp; <b>Effectif :</b> ${students.length} &nbsp; <b>Filles :</b> ${girls} &nbsp; <b>Garçons :</b> ${boys}</p><div class="table-wrap"><table><thead><tr><th>N°</th><th>NISU</th><th>Nom</th><th>Prénom</th><th>Sexe</th><th>Statut</th></tr></thead><tbody>${students.map((s,i)=>`<tr><td>${i+1}</td><td>${esc(s.nisu||'')}</td><td>${esc(s.lastName||'')}</td><td>${esc(s.firstName||'')}</td><td>${esc(s.sex||'')}</td><td>${esc(s.status||'')}</td></tr>`).join('')||'<tr><td colspan="6">Aucun élève.</td></tr>'}</tbody></table></div></div>`}
function printClassList(){renderClassList();const w=window.open('','_blank','width=900,height=1000');if(!w)return;const box=classListPreview.querySelector('.panel');w.document.write(`<html><head><title>Liste de classe ${esc(classListSelect.value)}</title><style>body{font-family:Arial;padding:25px}h1{font-size:22px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:7px}th{background:#e8f1ed}</style></head><body><h1>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h1>${box?box.outerHTML:''}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}

function printHTML(title,body,orientation='portrait'){const w=window.open('','_blank','width=1000,height=900');if(!w)return toast('Autorisez les fenêtres contextuelles pour imprimer.');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4 ${orientation};margin:12mm}body{font-family:Arial,sans-serif;color:#1d2b26}h1,h2{color:#176b52}table{width:100%;border-collapse:collapse}th,td{border:1px solid #aaa;padding:6px}th{background:#e8f1ed}.exam-sheet{white-space:pre-wrap;line-height:1.5}.meta{padding:10px;background:#f1f6f3;border:1px solid #cbd8d2;margin:10px 0}.sign{display:flex;justify-content:space-between;margin-top:45px}</style></head><body><h1>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h1>${body}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function downloadText(filename,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function examHTML(x){return `<h2>${esc(x.title||x.subject)}</h2><div class="meta"><b>Année :</b> ${esc(x.year)} &nbsp; <b>Classe :</b> ${esc(x.class)} &nbsp; <b>Matière :</b> ${esc(x.subject)}<br><b>Type :</b> ${esc(x.type)} &nbsp; <b>Date :</b> ${esc(x.date||'—')} &nbsp; <b>Durée :</b> ${esc(x.duration||'—')} &nbsp; <b>Barème :</b> ${esc(x.max)} points<br><b>Enseignant :</b> ${esc(x.teacher||'—')}</div>${x.instructions?`<h3>Consignes générales</h3><div class="exam-sheet">${esc(x.instructions)}</div>`:''}<h3>Épreuve</h3><div class="exam-sheet">${esc(x.content)}</div><div class="sign"><span>Élève : __________________</span><span>Enseignant : __________________</span></div>`}
function renderExams(){const q=(examSearch.value||'').toLowerCase();examsBody.innerHTML=data.exams.filter(x=>[x.year,x.class,x.subject,x.type,x.title].join(' ').toLowerCase().includes(q)).slice().reverse().map(x=>`<tr><td>${esc(x.year)}</td><td>${esc(x.class)}</td><td>${esc(x.subject)}</td><td>${esc(x.type)}</td><td>${esc(x.date||'—')}</td><td>${esc(x.max)}</td><td><button class="btn mini" data-exam-edit="${x.id}">Modifier</button> <button class="btn mini" data-exam-print="${x.id}">Imprimer</button> <button class="btn mini" data-exam-download="${x.id}">Télécharger</button> <button class="btn mini danger" data-exam-delete="${x.id}">Supprimer</button></td></tr>`).join('')||'<tr><td colspan="7">Aucune épreuve enregistrée.</td></tr>';
document.querySelectorAll('[data-exam-edit]').forEach(b=>b.onclick=()=>editExam(b.dataset.examEdit));document.querySelectorAll('[data-exam-print]').forEach(b=>b.onclick=()=>{const x=data.exams.find(e=>e.id===b.dataset.examPrint);if(x)printHTML('Épreuve '+x.subject,examHTML(x))});document.querySelectorAll('[data-exam-download]').forEach(b=>b.onclick=()=>{const x=data.exams.find(e=>e.id===b.dataset.examDownload);if(x)downloadText(`IMDS-Epreuve-${(x.subject||'examen').replace(/\s+/g,'-')}-${x.year}.html`,`<!doctype html><html lang="fr"><meta charset="utf-8"><title>${esc(x.title||x.subject)}</title><body><h1>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h1>${examHTML(x)}</body></html>`,'text/html')});document.querySelectorAll('[data-exam-delete]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cette épreuve ?')){data.exams=data.exams.filter(e=>e.id!==b.dataset.examDelete);save();toast('Épreuve supprimée')}})}
function editExam(id){const x=data.exams.find(e=>e.id===id);if(!x)return;examForm.dataset.edit=id;examYear.value=x.year||'2026-2027';examClass.value=x.class||'1re AF';examSubject.value=x.subject||'';examType.value=x.type||'Contrôle';examDate.value=x.date||'';examDuration.value=x.duration||'';examTeacher.value=x.teacher||'';examMax.value=x.max||100;examTitle.value=x.title||'';examInstructions.value=x.instructions||'';examContent.value=x.content||'';showSection('exams');window.scrollTo({top:0,behavior:'smooth'});toast('Mode modification de l’épreuve activé')}
examForm.onsubmit=e=>{e.preventDefault();const x={id:examForm.dataset.edit||uid(),year:examYear.value.trim(),class:examClass.value,subject:examSubject.value.trim(),type:examType.value,date:examDate.value,duration:examDuration.value.trim(),teacher:examTeacher.value.trim(),max:Number(examMax.value)||0,title:examTitle.value.trim(),instructions:examInstructions.value.trim(),content:examContent.value.trim(),updatedAt:today()};if(!x.subject||!x.content)return toast('Matière et contenu de l’épreuve sont obligatoires.');const i=data.exams.findIndex(e=>e.id===x.id);if(i>=0)data.exams[i]=x;else data.exams.push(x);delete examForm.dataset.edit;examForm.reset();examYear.value='2026-2027';examMax.value=100;save();toast(i>=0?'Épreuve modifiée':'Épreuve enregistrée')};resetExamBtn.onclick=()=>{delete examForm.dataset.edit;examForm.reset();examYear.value='2026-2027';examMax.value=100};printExamBtn.onclick=()=>{const x={year:examYear.value,class:examClass.value,subject:examSubject.value,type:examType.value,date:examDate.value,duration:examDuration.value,teacher:examTeacher.value,max:examMax.value,title:examTitle.value,instructions:examInstructions.value,content:examContent.value};if(!x.subject||!x.content)return toast('Saisissez l’épreuve avant de l’imprimer.');printHTML('Épreuve '+x.subject,examHTML(x))};downloadExamBtn.onclick=()=>{const x={year:examYear.value,class:examClass.value,subject:examSubject.value,type:examType.value,date:examDate.value,duration:examDuration.value,teacher:examTeacher.value,max:examMax.value,title:examTitle.value,instructions:examInstructions.value,content:examContent.value};if(!x.subject||!x.content)return toast('Saisissez l’épreuve avant de la télécharger.');downloadText(`IMDS-Epreuve-${x.subject.replace(/\s+/g,'-')}-${x.year}.html`,`<!doctype html><html lang="fr"><meta charset="utf-8"><title>${esc(x.title||x.subject)}</title><body><h1>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h1>${examHTML(x)}</body></html>`,'text/html')};examSearch.oninput=renderExams;
function palmaresRows(){const cls=palmaresClass.value,year=palmaresYear.value.trim(),period=palmaresPeriod.value;const students=data.students.filter(s=>s.class===cls&&s.status!=='transféré'&&s.status!=='abandonné');const subjects=[...new Set(data.grades.filter(g=>g.year===year&&g.period===period&&students.some(s=>s.id===g.studentId)).map(g=>g.subject))];const rows=students.map(s=>{const gs=gradesForStudent(s.id,year,period);const total=gs.reduce((a,g)=>a+Number(g.value||0),0),possible=gs.reduce((a,g)=>a+Number(g.maxScore||100),0),avg=possible?total/possible*10:0;const vals=subjects.map(sub=>{const g=gs.find(x=>x.subject===sub);return g?`${g.value}/${g.maxScore}`:'—'});return {s,total,possible,avg,vals}}).sort((a,b)=>b.avg-a.avg);rows.forEach((r,i)=>r.rank=r.avg>0?i+1:null);return {rows,subjects,cls,year,period}}
function renderPalmares(){const p=palmaresRows();palmaresPreview.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Rang</th><th>Élève</th>${p.subjects.map(s=>`<th>${esc(s)}</th>`).join('')}<th>Total</th><th>Possible</th><th>Moy. /10</th></tr></thead><tbody>${p.rows.map(r=>`<tr><td>${r.rank||'—'}</td><td>${esc(r.s.fullName)}</td>${r.vals.map(v=>`<td>${esc(v)}</td>`).join('')}<td>${r.total.toFixed(2)}</td><td>${r.possible.toFixed(2)}</td><td><b>${r.avg.toFixed(2)}</b></td></tr>`).join('')||'<tr><td colspan="8">Aucun résultat.</td></tr>'}</tbody></table></div>`}
function printPalmares(){const p=palmaresRows();const table=`<h2>PALMARÈS DES NOTES</h2><div class="meta"><b>Année :</b> ${esc(p.year)} &nbsp; <b>Classe :</b> ${esc(p.cls)} &nbsp; <b>Période :</b> ${esc(p.period)}</div><table><thead><tr><th>Rang</th><th>Élève</th>${p.subjects.map(s=>`<th>${esc(s)}</th>`).join('')}<th>Total</th><th>Possible</th><th>Moy. /10</th></tr></thead><tbody>${p.rows.map(r=>`<tr><td>${r.rank||'—'}</td><td>${esc(r.s.fullName)}</td>${r.vals.map(v=>`<td>${esc(v)}</td>`).join('')}<td>${r.total.toFixed(2)}</td><td>${r.possible.toFixed(2)}</td><td>${r.avg.toFixed(2)}</td></tr>`).join('')}</tbody></table>`;printHTML('Palmarès des notes',table,'landscape')}
function downloadPalmares(){const p=palmaresRows();const header=['Rang','Élève',...p.subjects,'Total obtenu','Total possible','Moyenne /10'];const lines=[header,...p.rows.map(r=>[r.rank||'',r.s.fullName,...r.vals,r.total.toFixed(2),r.possible.toFixed(2),r.avg.toFixed(2)])].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');downloadText(`IMDS-Palmares-${p.cls}-${p.year}-${p.period}.csv`,lines,'text/csv;charset=utf-8');toast('Palmarès téléchargé')}
previewPalmaresBtn.onclick=renderPalmares;printPalmaresBtn.onclick=printPalmares;downloadPalmaresBtn.onclick=downloadPalmares;[palmaresYear,palmaresClass,palmaresPeriod].forEach(x=>x.onchange=renderPalmares);

// v4.4 — référentiel pédagogique et administration
const PEDAGOGY={
 'Français':['Grammaire et conjugaison','Vocabulaire et orthographe','Communication orale','Dictée','Production écrite'],
 'Kreyòl':['Gramè ak konjigezon','Vokabilè ak òtograf','Kominikasyon oral','Dikte','Pwodiksyon ekri'],
 'Mathématiques':['Numération','Opérations','Mesure','Géométrie','Problèmes','Calcul mental','Algèbre','Statistiques'],
 'Anglais':[],'Espagnol':[],'Créole':[],'EPS':[],'EEA':[],'ITAP':[],
 'Sciences sociales':['Géographie','Histoire','Éducation civique'],
 'Sciences expérimentales':[],'Biologie':[],'Physique':[],
 'Éducation à la citoyenneté':[],'Éducation chrétienne / Bible':[]
};
const ALL_CLASSES=['Kindergarten 1','Kindergarten 2','Kindergarten 3','1re AF','2e AF','3e AF','4e AF','5e AF','6e AF','7e AF','8e AF','9e AF'];
function populatePlanningSubjects(){
  const selects=[planningSubject,planningFilterSubject];
  selects.forEach(sel=>{if(!sel)return;const current=sel.value;sel.innerHTML=(sel===planningFilterSubject?'<option value="">Toutes</option>':'')+Object.keys(PEDAGOGY).map(x=>`<option>${esc(x)}</option>`).join('');if(current&&[...sel.options].some(o=>o.value===current))sel.value=current;});
  updatePlanningSubSubjects();
}
function updatePlanningSubSubjects(){if(!planningSubSubject)return;const subs=PEDAGOGY[planningSubject.value]||[];planningSubSubject.innerHTML='<option value="">Matière générale</option>'+subs.map(x=>`<option>${esc(x)}</option>`).join('');}
function planningObjectFromForm(){return {id:planningForm.dataset.edit||uid(),type:planningType.value,year:planningYear.value.trim(),class:planningClass.value,subject:planningSubject.value,subSubject:planningSubSubject.value,teacher:planningTeacher.value.trim(),period:planningPeriod.value.trim(),date:planningDate.value,duration:planningDuration.value.trim(),theme:planningTheme.value.trim(),objective:planningObjective.value.trim(),prerequisite:planningPrerequisite.value.trim(),method:planningMethod.value.trim(),activities:planningActivities.value.trim(),materials:planningMaterials.value.trim(),evaluation:planningEvaluation.value.trim(),remediation:planningRemediation.value.trim(),homework:planningHomework.value.trim(),observations:planningObservations.value.trim(),updatedAt:today()};}
function planningHTML(x){return `<h2>${esc(x.type)}</h2><div class="meta"><b>Année :</b> ${esc(x.year)} &nbsp; <b>Classe :</b> ${esc(x.class)}<br><b>Matière :</b> ${esc(x.subject)}${x.subSubject?` / ${esc(x.subSubject)}`:''} &nbsp; <b>Enseignant :</b> ${esc(x.teacher||'—')}<br><b>Période :</b> ${esc(x.period||'—')} &nbsp; <b>Date :</b> ${esc(x.date||'—')} &nbsp; <b>Durée :</b> ${esc(x.duration||'—')}</div>${[['Thème / chapitre',x.theme],['Objectif / compétence',x.objective],['Prérequis',x.prerequisite],['Méthode pédagogique',x.method],['Déroulement / activités',x.activities],['Matériel / supports',x.materials],['Évaluation',x.evaluation],['Remédiation',x.remediation],['Devoir / travail à domicile',x.homework],['Observations',x.observations]].filter(a=>a[1]).map(a=>`<h3>${a[0]}</h3><div class="exam-sheet">${esc(a[1])}</div>`).join('')}<div class="sign"><span>Enseignant : __________________</span><span>Direction : __________________</span></div>`}
function renderPlanning(){const q=(planningSearch.value||'').toLowerCase(),fc=planningFilterClass.value,ft=planningFilterType.value,fs=planningFilterSubject.value;planningBody.innerHTML=data.planning.filter(x=>(!fc||x.class===fc)&&(!ft||x.type===ft)&&(!fs||x.subject===fs)&&[x.subject,x.subSubject,x.teacher,x.theme,x.objective,x.year,x.period].join(' ').toLowerCase().includes(q)).slice().reverse().map(x=>`<tr><td>${esc(x.type)}</td><td>${esc(x.year)}</td><td>${esc(x.class)}</td><td>${esc(x.subject)}</td><td>${esc(x.subSubject||'—')}</td><td>${esc(x.teacher||'—')}</td><td>${esc(x.period||'—')}</td><td><button class="btn mini" data-plan-edit="${x.id}">Modifier</button> <button class="btn mini" data-plan-print="${x.id}">Imprimer</button> <button class="btn mini" data-plan-download="${x.id}">Télécharger</button> <button class="btn mini danger" data-plan-delete="${x.id}">Supprimer</button></td></tr>`).join('')||'<tr><td colspan="8">Aucune planification enregistrée.</td></tr>';document.querySelectorAll('[data-plan-edit]').forEach(b=>b.onclick=()=>editPlanning(b.dataset.planEdit));document.querySelectorAll('[data-plan-print]').forEach(b=>b.onclick=()=>{const x=data.planning.find(p=>p.id===b.dataset.planPrint);if(x)printHTML('Planification pédagogique',planningHTML(x))});document.querySelectorAll('[data-plan-download]').forEach(b=>b.onclick=()=>{const x=data.planning.find(p=>p.id===b.dataset.planDownload);if(x)downloadText(`IMDS-Planification-${(x.class||'classe').replace(/\\s+/g,'-')}-${x.year}.html`,`<!doctype html><html lang="fr"><meta charset="utf-8"><title>Planification IMDS</title><body><h1>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h1>${planningHTML(x)}</body></html>`,'text/html')});document.querySelectorAll('[data-plan-delete]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cette planification ?')){data.planning=data.planning.filter(x=>x.id!==b.dataset.planDelete);save();logAdmin('Suppression d’une planification');toast('Planification supprimée')}})}
function editPlanning(id){const x=data.planning.find(p=>p.id===id);if(!x)return;planningForm.dataset.edit=id;planningType.value=x.type;planningYear.value=x.year;planningClass.value=x.class;planningSubject.value=x.subject;updatePlanningSubSubjects();planningSubSubject.value=x.subSubject||'';planningTeacher.value=x.teacher||'';planningPeriod.value=x.period||'';planningDate.value=x.date||'';planningDuration.value=x.duration||'';planningTheme.value=x.theme||'';planningObjective.value=x.objective||'';planningPrerequisite.value=x.prerequisite||'';planningMethod.value=x.method||'';planningActivities.value=x.activities||'';planningMaterials.value=x.materials||'';planningEvaluation.value=x.evaluation||'';planningRemediation.value=x.remediation||'';planningHomework.value=x.homework||'';planningObservations.value=x.observations||'';showSection('planning');toast('Mode modification activé')}
function resetPlanning(){delete planningForm.dataset.edit;planningForm.reset();planningYear.value='2026-2027';populatePlanningSubjects();}
function adminRolePermissions(role){return {'Administrateur principal':'Tous les modules, comptes, paramètres et sauvegardes','Direction':'Élèves, finances, enseignants, pédagogie, notes, examens et rapports','Censeur':'Élèves, classes, présences, discipline, notes et bulletins','Secrétariat':'Élèves, inscriptions, documents, paiements et reçus','Économat / Comptabilité':'Paiements, recettes, dépenses et rapports financiers','Enseignant':'Classes, planifications, notes et présences autorisées','Consultation':'Consultation uniquement'}[role]||''}
async function hashPassword(v){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function logAdmin(action,user='Administrateur local'){data.adminLogs=(data.adminLogs||[]);data.adminLogs.push({id:uid(),date:new Date().toLocaleString('fr-FR'),user,action});data.adminLogs=data.adminLogs.slice(-200)}
function renderAdmins(){adminBody.innerHTML=(data.admins||[]).slice().reverse().map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.username)}</td><td>${esc(x.role)}</td><td>${esc(x.phone||'—')}</td><td>${esc(x.status)}</td><td><button class="btn mini" data-admin-edit="${x.id}">Modifier</button> <button class="btn mini danger" data-admin-delete="${x.id}">Supprimer</button></td></tr>`).join('')||'<tr><td colspan="6">Aucun compte enregistré.</td></tr>';adminLogBody.innerHTML=(data.adminLogs||[]).slice().reverse().slice(0,100).map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.user)}</td><td>${esc(x.action)}</td></tr>`).join('')||'<tr><td colspan="3">Aucune action enregistrée.</td></tr>';document.querySelectorAll('[data-admin-edit]').forEach(b=>b.onclick=()=>{const x=data.admins.find(a=>a.id===b.dataset.adminEdit);if(!x)return;adminForm.dataset.edit=x.id;adminName.value=x.name;adminUsername.value=x.username;adminPassword.value='';adminRole.value=x.role;adminPhone.value=x.phone||'';adminStatus.value=x.status;showSection('administration')});document.querySelectorAll('[data-admin-delete]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer ce compte ?')){data.admins=data.admins.filter(a=>a.id!==b.dataset.adminDelete);logAdmin('Suppression d’un compte');save();toast('Compte supprimé')}})}
planningSubject.onchange=updatePlanningSubSubjects;planningForm.onsubmit=async e=>{e.preventDefault();const x=planningObjectFromForm();if(!x.subject||!x.theme)return toast('La matière et le thème sont obligatoires.');const i=data.planning.findIndex(p=>p.id===x.id);if(i>=0)data.planning[i]=x;else data.planning.push(x);delete planningForm.dataset.edit;save();logAdmin(i>=0?'Modification d’une planification':'Création d’une planification');save();renderPlanning();toast(i>=0?'Planification modifiée':'Planification enregistrée')};resetPlanningBtn.onclick=resetPlanning;printPlanningBtn.onclick=()=>{const x=planningObjectFromForm();if(!x.subject||!x.theme)return toast('Saisissez une planification avant de l’imprimer.');printHTML('Planification pédagogique',planningHTML(x))};downloadPlanningBtn.onclick=()=>{const x=planningObjectFromForm();if(!x.subject||!x.theme)return toast('Saisissez une planification avant de la télécharger.');downloadText(`IMDS-Planification-${x.class}-${x.year}.html`,`<!doctype html><html lang="fr"><meta charset="utf-8"><title>Planification IMDS</title><body><h1>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h1>${planningHTML(x)}</body></html>`,'text/html')};[planningFilterClass,planningFilterType,planningFilterSubject].forEach(x=>x.onchange=renderPlanning);planningSearch.oninput=renderPlanning;
adminForm.onsubmit=async e=>{e.preventDefault();const id=adminForm.dataset.edit||uid(),old=data.admins.find(a=>a.id===id),password=adminPassword.value.trim();if(!old&&!password)return toast('Le mot de passe est obligatoire.');const rec={id,name:adminName.value.trim(),username:adminUsername.value.trim(),role:adminRole.value,phone:adminPhone.value.trim(),status:adminStatus.value,updatedAt:today()};if(password)rec.passwordHash=await hashPassword(password);else rec.passwordHash=old.passwordHash;const i=data.admins.findIndex(a=>a.id===id);if(i>=0)data.admins[i]=rec;else data.admins.push(rec);logAdmin(i>=0?'Modification d’un compte':'Création d’un compte',rec.username);save();delete adminForm.dataset.edit;adminForm.reset();renderAdmins();toast(i>=0?'Compte modifié':'Compte créé')};resetAdminBtn.onclick=()=>{delete adminForm.dataset.edit;adminForm.reset()};

function renderAll(){renderStudents();fillSelects();renderPayments();renderFinance();renderGrades();renderAttendance();renderSocial();renderBulletinPreview();renderClassList();renderReceiptPreview();renderTeachers();renderExpenses();renderMonthlyReport();renderExams();renderPalmares();populatePlanningSubjects();renderPlanning();renderAdmins()}
gradeYear.oninput=()=>{bulletinYear.value=gradeYear.value};bulletinClassFilter.onchange=renderGrades;bulletinPeriodFilter.onchange=renderGrades;bulletinStudent.onchange=renderBulletinPreview;bulletinYear.onchange=renderBulletinPreview;bulletinPeriod.onchange=renderBulletinPreview;previewBulletin.onclick=renderBulletinPreview;printBulletin.onclick=()=>printOneBulletin(bulletinStudent.value);generateClassBulletins.onclick=printClassBulletins;classListSelect.onchange=renderClassList;classListYear.oninput=renderClassList;printClassList.onclick=printClassList;studentSearch.oninput=renderStudents;resetStudentBtn.onclick=()=>{delete studentForm.dataset.edit;photoPreview.src='';photoPreview.classList.add('hidden')};initDepartments();renderAll();renderClassList();renderBulletinPreview();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));

/* ===== IMDS v4.5 — Synchronisation multi-appareils ===== */
const IMDS_SYNC_KEY='imds_sync_config_v45';
const IMDS_DEVICE_KEY='imds_sync_device_v45';
let imdsSupabase=null;
let imdsSyncTimer=null;
let imdsSyncBusy=false;

function syncCfg(){try{return JSON.parse(localStorage.getItem(IMDS_SYNC_KEY)||'{}')}catch{return {}}}
function saveSyncCfg(c){localStorage.setItem(IMDS_SYNC_KEY,JSON.stringify(c))}
function syncDeviceId(){let id=localStorage.getItem(IMDS_DEVICE_KEY);if(!id){id='IMDS-'+uid();localStorage.setItem(IMDS_DEVICE_KEY,id)}return id}
function syncSetMessage(msg,type=''){const el=document.getElementById('syncMessage');if(el){el.textContent=msg;el.className='message '+type}}
function syncSetStatus(msg,type=''){const el=document.getElementById('syncStatus');if(el){el.textContent=msg;el.className='message '+type}}
function syncIsConfigured(){const c=syncCfg();return !!(c.url&&c.key&&c.schoolId)}
function syncClient(){return imdsSupabase}

async function initSupabaseClient(){
  const c=syncCfg();
  if(!c.url||!c.key||!window.supabase){imdsSupabase=null;return null}
  try{
    imdsSupabase=window.supabase.createClient(c.url,c.key,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});
    const {data}=await imdsSupabase.auth.getSession();
    if(data?.session) syncSetStatus('Connecté au cloud','ok');
    else syncSetStatus('Configuration enregistrée — connexion requise','warn');
    return imdsSupabase;
  }catch(e){imdsSupabase=null;syncSetStatus('Configuration cloud invalide : '+e.message,'error');return null}
}

function fillSyncForm(){
  const c=syncCfg();
  if(document.getElementById('syncUrl')) syncUrl.value=c.url||'';
  if(document.getElementById('syncKey')) syncKey.value=c.key||'';
  if(document.getElementById('syncSchoolId')) syncSchoolId.value=c.schoolId||'IMDS';
  if(document.getElementById('syncDevice')) syncDevice.textContent=syncDeviceId();
}

async function syncSession(){return imdsSupabase? (await imdsSupabase.auth.getSession()).data.session:null}
function cloudPayload(){return {schemaVersion:1,appVersion:'4.5',data:JSON.parse(JSON.stringify(data))}}

async function cloudRow(){
  if(!imdsSupabase) return {row:null,error:new Error('Supabase non configuré')};
  const c=syncCfg();
  const {data:rows,error}=await imdsSupabase.from('imds_sync_snapshots').select('*').eq('school_id',c.schoolId).limit(1);
  return {row:rows?.[0]||null,error};
}

function localStamp(){return Number(localStorage.getItem('imds_sync_local_stamp_v45')||0)}
function setLocalStamp(v){localStorage.setItem('imds_sync_local_stamp_v45',String(v||Date.now()))}

async function syncPush(force=false){
  if(imdsSyncBusy)return false;
  const session=await syncSession();
  if(!session){syncSetMessage('Connectez-vous d’abord au compte cloud.','warn');return false}
  if(!navigator.onLine){syncSetMessage('Hors connexion : les données restent enregistrées localement.','warn');return false}
  imdsSyncBusy=true;
  try{
    const c=syncCfg();
    const remote=await cloudRow();
    if(remote.error)throw remote.error;
    const stamp=localStamp()||0;
    if(remote.row && !force && Number(new Date(remote.row.updated_at).getTime())>stamp && stamp>0){
      syncSetMessage('Une version cloud plus récente existe. Récupérez-la avant d’envoyer vos modifications, ou utilisez « Envoyer vers le cloud » après vérification.','warn');return false;
    }
    const payload=cloudPayload();
    const now=Date.now();
    const row={school_id:c.schoolId,payload,updated_at:new Date(now).toISOString(),updated_by:session.user.id,device_id:syncDeviceId(),revision:Number(remote.row?.revision||0)+1};
    const {error}=await imdsSupabase.from('imds_sync_snapshots').upsert(row,{onConflict:'school_id'});
    if(error)throw error;
    setLocalStamp(now);
    document.getElementById('syncLast').textContent=new Date(now).toLocaleString('fr-FR');
    document.getElementById('syncState').textContent='Synchronisé';
    syncSetMessage('Données envoyées vers le cloud avec succès.','ok');
    return true;
  }catch(e){syncSetMessage('Échec de l’envoi : '+e.message,'error');return false}
  finally{imdsSyncBusy=false}
}

async function syncPull(force=false){
  if(imdsSyncBusy)return false;
  const session=await syncSession();
  if(!session){syncSetMessage('Connectez-vous d’abord au compte cloud.','warn');return false}
  if(!navigator.onLine){syncSetMessage('Hors connexion : impossible de récupérer le cloud.','warn');return false}
  imdsSyncBusy=true;
  try{
    const remote=await cloudRow();
    if(remote.error)throw remote.error;
    if(!remote.row){syncSetMessage('Aucune sauvegarde cloud pour cette école.','warn');return false}
    const remoteStamp=new Date(remote.row.updated_at).getTime();
    if(!force && localStamp()>remoteStamp){syncSetMessage('Votre appareil contient une version locale plus récente. Envoyez-la après vérification si nécessaire.','warn');return false}
    if(!remote.row.payload?.data?.students)throw new Error('Sauvegarde cloud invalide');
    data=remote.row.payload.data;
    localStorage.setItem(KEY,JSON.stringify(data));
    setLocalStamp(remoteStamp);
    renderAll();
    document.getElementById('syncLast').textContent=new Date(remoteStamp).toLocaleString('fr-FR');
    document.getElementById('syncState').textContent='Synchronisé';
    syncSetMessage('Données récupérées depuis le cloud.','ok');
    return true;
  }catch(e){syncSetMessage('Échec de récupération : '+e.message,'error');return false}
  finally{imdsSyncBusy=false}
}

async function syncNow(){
  if(!syncIsConfigured())return syncSetMessage('Configurez d’abord l’URL Supabase, la clé publishable et l’identifiant de l’école.','warn');
  if(!imdsSupabase)await initSupabaseClient();
  const session=await syncSession();
  if(!session)return syncSetMessage('Connectez-vous au compte cloud avant de synchroniser.','warn');
  const remote=await cloudRow();
  if(remote.error)return syncSetMessage('Impossible de lire le cloud : '+remote.error.message,'error');
  if(!remote.row)return syncPush(true);
  const r=new Date(remote.row.updated_at).getTime(), l=localStamp();
  if(r>l&&l>0){syncSetMessage('Le cloud est plus récent. Utilisez « Récupérer depuis le cloud » pour éviter d’écraser les données.','warn');return false}
  return syncPush(false);
}

async function syncLogin(){
  if(!imdsSupabase)await initSupabaseClient();
  if(!imdsSupabase)return syncSetStatus('Configurez d’abord Supabase.','warn');
  const email=syncEmail.value.trim(), password=syncPassword.value;
  if(!email||!password)return syncSetStatus('Email et mot de passe requis.','warn');
  try{
    const {error}=await imdsSupabase.auth.signInWithPassword({email,password});
    if(error)throw error;
    syncSetStatus('Connexion réussie.','ok');
    syncSetMessage('Compte cloud connecté. Vous pouvez synchroniser cet appareil.','ok');
    const s=await syncSession();if(s)syncUser.textContent=s.user.email||s.user.id;
    await syncPull(false);
  }catch(e){syncSetStatus('Échec de connexion : '+e.message,'error')}
}
async function syncLogout(){if(!imdsSupabase)return;await imdsSupabase.auth.signOut();syncSetStatus('Déconnecté — mode local disponible.','warn');syncUser.textContent='—';document.getElementById('syncState').textContent='Local uniquement'}

function scheduleCloudSync(){
  if(!syncIsConfigured()||!imdsSupabase||!navigator.onLine)return;
  clearTimeout(imdsSyncTimer);
  imdsSyncTimer=setTimeout(()=>syncNow().catch(()=>{}),1800);
}

const _imdsOriginalSave=save;
save=function(){_imdsOriginalSave();scheduleCloudSync()}

function initSyncModule(){
  fillSyncForm();
  syncConfigForm.onsubmit=async e=>{e.preventDefault();saveSyncCfg({url:syncUrl.value.trim().replace(/\/$/,''),key:syncKey.value.trim(),schoolId:syncSchoolId.value.trim()||'IMDS'});await initSupabaseClient();syncSetMessage('Configuration enregistrée sur cet appareil.','ok')};
  syncLoginBtn.onclick=syncLogin;syncLogoutBtn.onclick=syncLogout;syncNowBtn.onclick=syncNow;syncPullBtn.onclick=()=>syncPull(true);syncPushBtn.onclick=()=>syncPush(true);
  window.addEventListener('online',()=>{syncSetStatus(syncIsConfigured()?'Connexion Internet détectée.':'Mode local','ok');if(syncIsConfigured())initSupabaseClient()});
  window.addEventListener('offline',()=>syncSetStatus('Hors connexion — les données restent disponibles localement.','warn'));
  if(syncIsConfigured())initSupabaseClient();
  if(imdsSupabase)imdsSupabase.auth.onAuthStateChange((_event,session)=>{syncUser.textContent=session?.user?.email||'—';syncState.textContent=session?'Connecté':'Local uniquement'});
}

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initSyncModule);else initSyncModule();
