const KEY='imds_school_manager_v4';
const defaultData={students:[],payments:[],grades:[],attendance:[],social:[],teachers:[],teacherPayments:[],meta:{nextReceipt:1,nextTeacherReceipt:1}};
let data=loadData();
const departments={
'Ouest':['Port-au-Prince','Delmas','Pétion-Ville','Kenscoff','Carrefour','Gressier','Léogâne','Grand-Goâve','Petit-Goâve','Fonds-Verrettes','Cornillon','Thomazeau','Ganthier','Croix-des-Bouquets','Cité Soleil','Tabarre','Cabaret','Arcahaie','Anse-à-Galets','Pointe-à-Raquette'],
'Sud-Est':['Jacmel','Cayes-Jacmel','La Vallée-de-Jacmel','Marigot','Bainet','Côtes-de-Fer','Belle-Anse','Anse-à-Pitres','Thiotte','Grand-Gosier'],
'Nord':['Cap-Haïtien','Limonade','Quartier-Morin','Acul-du-Nord','Plaine-du-Nord','Milot','Grande-Rivière-du-Nord','Dondon','Saint-Raphaël','Pignon','La Victoire','Ranquitte','Borgne','Port-Margot','Limbé','Bas-Limbé','Plaisance','Pilate','Bahon'],
'Nord-Est':['Fort-Liberté','Ferrier','Perches','Ouanaminthe','Capotille','Mont-Organisé','Trou-du-Nord','Caracol','Sainte-Suzanne','Terrier-Rouge','Vallières','Carice','Mombin-Crochu'],
'Artibonite':['Gonaïves','Ennery','L’Estère','Gros-Morne','Terre-Neuve','Anse-Rouge','Saint-Marc','Verrettes','La Chapelle','Dessalines','Desdunes','Grande-Saline','Petite-Rivière-de-l’Artibonite','Marmelade','Saint-Michel-de-l’Attalaye','Liancourt','Montrouis'],
'Centre':['Hinche','Cerca-la-Source','Cerca-Carvajal','Maïssade','Thomonde','Thomassique','Mirebalais','Saut-d’Eau','Boucan-Carré','Lascahobas','Belladère','Savanette','Baptiste'],
'Sud':['Les Cayes','Torbeck','Chantal','Camp-Perrin','Maniche','Île-à-Vache','Port-Salut','Saint-Jean-du-Sud','Arniquet','Aquin','Saint-Louis-du-Sud','Cavaillon','Les Côteaux','Port-à-Piment','Roche-à-Bateau','Chardonnières','Les Anglais','Tiburon'],
'Grande-Anse':['Jérémie','Abricots','Bonbon','Chambellan','Moron','Marfranc','Anse-d’Hainault','Dame-Marie','Les Irois','Corail','Beaumont','Pestel','Roseaux'],
'Nord-Ouest':['Môle-Saint-Nicolas','Baie-de-Henne','Bombardopolis','Jean-Rabel','Port-de-Paix','Bassin-Bleu','Chansolme','La Tortue','La Pointe des Palmistes','Saint-Louis-du-Nord','Anse-à-Foleur'],
'Nippes':['Miragoâne','Petite-Rivière-de-Nippes','Fonds-des-Nègres','Paillant','Anse-à-Veau','Petit-Trou-de-Nippes','L’Asile','Arnaud','Baradères','Grand-Boucan','Plaisance-du-Sud']};
function loadData(){try{let d=JSON.parse(localStorage.getItem(KEY));if(!d){const old=JSON.parse(localStorage.getItem('imds_school_manager_v3')||'null');d=old}if(d&&d.students&&d.payments){const base=structuredClone(defaultData);return Object.assign(base,d,{teachers:Array.isArray(d.teachers)?d.teachers:[],teacherPayments:Array.isArray(d.teacherPayments)?d.teacherPayments:[],meta:Object.assign(base.meta,d.meta||{})})}return structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function money(n){return new Intl.NumberFormat('fr-FR').format(Number(n)||0)+' HTG'}
function today(){return new Date().toLocaleDateString('fr-CA')}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function studentName(id){const s=data.students.find(x=>x.id===id);return s?s.fullName:'Élève supprimé'}
function paidFor(id){return data.payments.filter(p=>p.studentId===id).reduce((a,p)=>a+Number(p.amount||0),0)}
function dueFor(s){return Number(s.annualRequested||0)+Number(s.previousBalance||0)}
function tariffAmount(type){return Number({normal:normalPrice.value,bourse:scholarshipPrice.value,demi:halfScholarshipPrice.value,special:specialPrice.value}[type]||0)}
function teacherPay(t){return t.type==='heure'?Number(t.hourlyRate||0)*Number(t.hoursWorked||0):Number(t.fullTimeSalary||0)}
function currentMonth(){return new Date().toLocaleDateString('fr-CA').slice(0,7)}
function getTeacherName(id){const t=data.teachers.find(x=>x.id===id);return t?t.name:'Professeur supprimé'}
function teacherReceipt(t){return `IMDS-P-${String(t).padStart(6,'0')}`}

function showSection(id){document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.section===id));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showSection(b.dataset.section));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showSection(b.dataset.go));
function initDepartments(){birthDepartment.innerHTML='<option value="">Choisir le département</option>'+Object.keys(departments).map(d=>`<option>${esc(d)}</option>`).join('')}
birthDepartment.onchange=()=>{const list=departments[birthDepartment.value]||[];birthCommune.disabled=!list.length;birthCommune.innerHTML='<option value="">Choisir la commune</option>'+list.map(c=>`<option>${esc(c)}</option>`).join('')}
tariffType.onchange=()=>{annualRequested.value=tariffAmount(tariffType.value)};[normalPrice,scholarshipPrice,halfScholarshipPrice,specialPrice].forEach(x=>x.oninput=()=>{if(tariffType.value)annualRequested.value=tariffAmount(tariffType.value)});
studentPhoto.onchange=()=>{const f=studentPhoto.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas'),max=360,scale=Math.min(1,max/Math.max(im.width,im.height));c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);photoPreview.src=c.toDataURL('image/jpeg',.78);photoPreview.classList.remove('hidden')};im.src=r.result};r.readAsDataURL(f)};
teacherMonth.value=currentMonth();
function updateTeacherPayPreview(){const type=teacherType.value;const amount=type==='heure'?Number(teacherHourlyRate.value||0)*Number(teacherHoursWorked.value||0):Number(teacherFullTimeSalary.value||0);teacherPayPreview.textContent=money(amount)}
[teacherType,teacherHourlyRate,teacherHoursWorked,teacherFullTimeSalary].forEach(x=>x.oninput=x.onchange=updateTeacherPayPreview);
teacherType.onchange=()=>{updateTeacherPayPreview();teacherHourlyRate.closest('label').style.opacity=teacherType.value==='heure'?'1':'.55';teacherFullTimeSalary.closest('label').style.opacity=teacherType.value==='plein_temps'?'1':'.55'};

function renderStudents(){const q=studentSearch.value.toLowerCase();const rows=data.students.filter(s=>[s.fullName,s.nisu,s.class].join(' ').toLowerCase().includes(q)).map(s=>{const p=paidFor(s.id),d=dueFor(s);return `<tr><td>${s.photo?`<img class="avatar" src="${s.photo}" alt="">`:''}${esc(s.fullName)}</td><td>${esc(s.nisu||'—')}</td><td>${esc(s.class)}</td><td>${esc(s.tariffType||'—')}</td><td>${money(d)}</td><td>${money(p)}</td><td>${money(Math.max(0,d-p))}</td><td><span class="status ${s.status}">${esc(s.status)}</span></td><td><button class="btn mini" data-edit="${s.id}">Modifier</button> <button class="btn mini danger" data-delete="${s.id}">Supprimer</button></td></tr>`}).join('');studentsBody.innerHTML=rows||'<tr><td colspan="9">Aucun élève enregistré.</td></tr>';
document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cet élève et tout son historique ?')){const id=b.dataset.delete;data.students=data.students.filter(s=>s.id!==id);data.payments=data.payments.filter(p=>p.studentId!==id);data.grades=data.grades.filter(g=>g.studentId!==id);data.attendance=data.attendance.filter(a=>a.studentId!==id);save();toast('Élève supprimé')}});
document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editStudent(b.dataset.edit))}
function editStudent(id){const s=data.students.find(x=>x.id===id);if(!s)return;Object.entries({nisu:s.nisu,lastName:s.lastName,firstName:s.firstName,birthDate:s.birthDate,sex:s.sex,birthPlace:s.birthPlace,address:s.address,motherName:s.motherName,fatherName:s.fatherName,guardianName:s.guardianName,guardianPhone:s.guardianPhone,guardianCIN:s.guardianCIN,referredBy:s.referredBy,normalPrice:s.normalPrice,scholarshipPrice:s.scholarshipPrice,halfScholarshipPrice:s.halfScholarshipPrice,specialPrice:s.specialPrice,tariffType:s.tariffType,annualRequested:s.annualRequested,previousBalance:s.previousBalance,studentStatus:s.status}).forEach(([id,v])=>{if(document.getElementById(id))document.getElementById(id).value=v??''});studentClass.value=s.class;birthDepartment.value=s.birthDepartment||'';birthDepartment.onchange();birthCommune.value=s.birthCommune||'';photoPreview.src=s.photo||'';photoPreview.classList.toggle('hidden',!s.photo);studentForm.dataset.edit=id;showSection('students');window.scrollTo({top:0,behavior:'smooth'});toast('Mode modification activé')}
function fillSelects(){const o=data.students.map(s=>`<option value="${s.id}">${esc(s.fullName)} — ${esc(s.class)}</option>`).join('')||'<option value="">Aucun élève</option>';['paymentStudent','gradeStudent','attendanceStudent'].forEach(id=>document.getElementById(id).innerHTML=o);receiptSelect.innerHTML=data.payments.slice().reverse().map(p=>`<option value="${p.id}">${esc(p.receiptNumber)} — ${esc(studentName(p.studentId))} — ${money(p.amount)}</option>`).join('')||'<option value="">Aucun paiement</option>'}
function renderPayments(){paymentsBody.innerHTML=data.payments.slice().reverse().map(p=>`<tr><td>${p.date}</td><td>${esc(p.receiptNumber)}</td><td>${esc(studentName(p.studentId))}</td><td>${esc(p.reason)}</td><td>${esc(p.mode)}</td><td>${money(p.amount)}</td><td><button class="btn mini" data-receipt="${p.id}">Reçu</button></td></tr>`).join('')||'<tr><td colspan="7">Aucun paiement.</td></tr>';document.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>{showSection('receipts');receiptSelect.value=b.dataset.receipt;renderReceiptPreview()})}
function renderFinance(){let due=0,paid=0,up=0,late=0;const rows=data.students.map(s=>{const d=dueFor(s),p=paidFor(s),bal=Math.max(0,d-p);due+=d;paid+=p;if(bal<=0)up++;else late++;return `<tr><td>${esc(s.fullName)}</td><td>${money(s.annualRequested)}</td><td>${money(s.previousBalance)}</td><td>${money(d)}</td><td>${money(p)}</td><td>${money(bal)}</td><td>${bal<=0?'À jour':'En retard'}</td></tr>`}).join('');financeBody.innerHTML=rows||'<tr><td colspan="7">Aucun élève.</td></tr>';financeDue.textContent=money(due);financePaid.textContent=money(paid);financeBalance.textContent=money(Math.max(0,due-paid));financeUp.textContent=up;financeLate.textContent=late;statStudents.textContent=data.students.length;statAnnual.textContent=money(paid);statBalance.textContent=money(Math.max(0,due-paid));statUpToDate.textContent=up;statLate.textContent=late;const ym=today().slice(0,7);statToday.textContent=money(data.payments.filter(p=>p.date===today()).reduce((a,p)=>a+Number(p.amount),0));statMonth.textContent=money(data.payments.filter(p=>p.date.startsWith(ym)).reduce((a,p)=>a+Number(p.amount),0))}
function renderGrades(){gradesBody.innerHTML=data.grades.slice().reverse().map(g=>`<tr><td>${esc(studentName(g.studentId))}</td><td>${esc(g.subject)}</td><td>${g.value}/100</td><td>${g.date}</td></tr>`).join('')||'<tr><td colspan="4">Aucune note.</td></tr>'}
function renderAttendance(){attendanceBody.innerHTML=data.attendance.slice().reverse().slice(0,100).map(a=>`<tr><td>${a.date}</td><td>${esc(studentName(a.studentId))}</td><td>${esc(a.status)}</td></tr>`).join('')||'<tr><td colspan="3">Aucune présence.</td></tr>';statAttendance.textContent=data.attendance.filter(a=>a.date===today()).length}
function renderSocial(){socialFeed.innerHTML=data.social.slice().reverse().map(p=>`<div class="social-post panel"><div><strong>${esc(p.author)}</strong><span>${p.date}</span></div><p>${esc(p.message)}</p></div>`).join('')||'<div class="panel">Aucune publication.</div>'}
function receiptHtml(p){const s=data.students.find(x=>x.id===p.studentId);return `<div class="receipt"><div class="receipt-head"><div><h2>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h2><p>REÇU DE PAIEMENT</p></div><strong>${esc(p.receiptNumber)}</strong></div><hr><p><b>Élève :</b> ${esc(s?.fullName||'')}</p><p><b>NISU :</b> ${esc(s?.nisu||'—')} &nbsp; <b>Classe :</b> ${esc(s?.class||'')}</p><p><b>Date :</b> ${p.date}</p><p><b>Motif :</b> ${esc(p.reason)}</p><p><b>Mode :</b> ${esc(p.mode)}</p><div class="amount-box">Montant payé : <strong>${money(p.amount)}</strong></div><p class="small">Merci pour votre paiement.</p><div class="signatures"><span>Signature responsable</span><span>Cachet / Signature IMDS</span></div></div>`}
function renderReceiptPreview(){const p=data.payments.find(x=>x.id===receiptSelect.value);receiptPreview.innerHTML=p?receiptHtml(p):'<p>Aucun paiement sélectionné.</p>'}
studentForm.onsubmit=e=>{e.preventDefault();const id=studentForm.dataset.edit||uid();const photo=photoPreview.src&&!photoPreview.classList.contains('hidden')?photoPreview.src:'';const obj={id,nisu:nisu.value.trim(),lastName:lastName.value.trim(),firstName:firstName.value.trim(),fullName:(lastName.value.trim()+' '+firstName.value.trim()).trim(),class:studentClass.value,birthDate:birthDate.value,sex:sex.value,birthPlace:birthPlace.value.trim(),birthDepartment:birthDepartment.value,birthCommune:birthCommune.value,address:address.value.trim(),motherName:motherName.value.trim(),fatherName:fatherName.value.trim(),guardianName:guardianName.value.trim(),guardianPhone:guardianPhone.value.trim(),guardianCIN:guardianCIN.value.trim(),referredBy:referredBy.value.trim(),normalPrice:Number(normalPrice.value)||0,scholarshipPrice:Number(scholarshipPrice.value)||0,halfScholarshipPrice:Number(halfScholarshipPrice.value)||0,specialPrice:Number(specialPrice.value)||0,tariffType:tariffType.value,annualRequested:Number(annualRequested.value)||0,previousBalance:Number(previousBalance.value)||0,status:studentStatus.value,photo:photo||(data.students.find(s=>s.id===id)?.photo||'')};const i=data.students.findIndex(s=>s.id===id);if(i>=0)data.students[i]=obj;else data.students.push(obj);delete studentForm.dataset.edit;studentForm.reset();annualRequested.value=0;photoPreview.src='';photoPreview.classList.add('hidden');save();toast(i>=0?'Dossier modifié':'Élève enregistré')};
resetStudentBtn.onclick=()=>{delete studentForm.dataset.edit;setTimeout(()=>{photoPreview.src='';photoPreview.classList.add('hidden')},0)};
studentSearch.oninput=renderStudents;
paymentForm.onsubmit=e=>{e.preventDefault();const sid=paymentStudent.value;if(!sid)return toast('Ajoutez d’abord un élève');const rn=receiptNumber.value.trim()||`IMDS-${String(data.meta.nextReceipt++).padStart(6,'0')}`;data.payments.push({id:uid(),studentId:sid,amount:Number(paymentAmount.value),reason:paymentReason.value,mode:paymentMode.value,receiptNumber:rn,note:paymentNote.value.trim(),date:today()});paymentForm.reset();save();toast('Paiement enregistré — reçu '+rn);showSection('receipts');receiptSelect.value=data.payments[data.payments.length-1].id;renderReceiptPreview()};
gradeForm.onsubmit=e=>{e.preventDefault();data.grades.push({id:uid(),studentId:gradeStudent.value,subject:gradeSubject.value.trim(),value:Number(gradeValue.value),date:today()});e.target.reset();save();toast('Note enregistrée')};attendanceForm.onsubmit=e=>{e.preventDefault();data.attendance.push({id:uid(),studentId:attendanceStudent.value,status:attendanceStatus.value,date:today()});save();toast('Présence enregistrée')};
socialForm.onsubmit=e=>{e.preventDefault();data.social.push({id:uid(),author:socialAuthor.value.trim(),message:socialMessage.value.trim(),date:new Date().toLocaleString('fr-FR')});e.target.reset();save();toast('Publication ajoutée')};
receiptSelect.onchange=renderReceiptPreview;previewReceiptBtn.onclick=renderReceiptPreview;printReceiptBtn.onclick=()=>{const p=data.payments.find(x=>x.id===receiptSelect.value);if(!p)return;const w=window.open('','_blank','width=800,height=900');w.document.write(`<html><head><title>${esc(p.receiptNumber)}</title><style>body{font-family:Arial;padding:30px}.receipt{max-width:680px;margin:auto;border:2px solid #176b52;padding:28px}.receipt-head{display:flex;justify-content:space-between;gap:20px}.receipt-head h2{font-size:20px}.amount-box{margin:25px 0;padding:18px;background:#f1f6f3;font-size:20px}.signatures{display:flex;justify-content:space-between;margin-top:70px}.small{color:#666}</style></head><body>${receiptHtml(p)}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()};
teacherForm.onsubmit=e=>{e.preventDefault();const obj={id:uid(),name:teacherName.value.trim(),sex:teacherSex.value,class:teacherClass.value.trim(),subjects:teacherSubjects.value.trim(),type:teacherType.value,hourlyRate:Number(teacherHourlyRate.value)||0,fullTimeSalary:Number(teacherFullTimeSalary.value)||0,hoursWorked:Number(teacherHoursWorked.value)||0,hoursAbsent:Number(teacherHoursAbsent.value)||0,daysAbsent:Number(teacherDaysAbsent.value)||0,dress:teacherDress.value,month:teacherMonth.value||currentMonth()};data.teachers.push(obj);save();toast('Professeur enregistré');e.target.reset();teacherMonth.value=currentMonth();teacherType.onchange()};
teacherSearch.oninput=renderTeachers;reportMonth.value=currentMonth();reportMonth.onchange=renderMonthlyReport;printMonthlyReport.onclick=printMonthly;
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`IMDS-sauvegarde-${today()}.json`;a.click();URL.revokeObjectURL(a.href);securityMessage.textContent='Sauvegarde exportée.'};
importFile.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.students||!x.payments)throw Error();data=Object.assign(structuredClone(defaultData),x);save();toast('Sauvegarde importée')}catch{alert('Fichier de sauvegarde invalide.')}};r.readAsText(f)};
clearBtn.onclick=()=>{if(confirm('ATTENTION : effacer toutes les données locales de l’IMDS sur cet appareil ?')){data=structuredClone(defaultData);save();toast('Données effacées')}};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden')});installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add('hidden')}};

function renderTeachers(){const q=(teacherSearch.value||'').toLowerCase();teachersBody.innerHTML=data.teachers.filter(t=>[t.name,t.sex,t.class,t.subjects].join(' ').toLowerCase().includes(q)).map(t=>{const pay=teacherPay(t);return `<tr><td>${esc(t.name)}</td><td>${esc(t.sex||'—')}</td><td>${esc(t.class||'—')}</td><td>${esc(t.subjects||'—')}</td><td>${t.type==='heure'?'Heure fournie':'Plein temps'}</td><td>${t.type==='heure'?Number(t.hoursWorked||0):'—'}</td><td>${Number(t.hoursAbsent||0)} h / ${Number(t.daysAbsent||0)} j</td><td>${esc(t.dress||'—')}</td><td>${money(pay)}</td><td><button class="btn mini" data-pay-teacher="${t.id}">Payer le mois</button> <button class="btn mini danger" data-delete-teacher="${t.id}">Supprimer</button></td></tr>`}).join('')||'<tr><td colspan="10">Aucun professeur enregistré.</td></tr>';
document.querySelectorAll('[data-delete-teacher]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer ce professeur et son historique de paiements ?')){const id=b.dataset.deleteTeacher;data.teachers=data.teachers.filter(t=>t.id!==id);data.teacherPayments=data.teacherPayments.filter(p=>p.teacherId!==id);save();toast('Professeur supprimé')}});
document.querySelectorAll('[data-pay-teacher]').forEach(b=>b.onclick=()=>payTeacher(b.dataset.payTeacher));
teacherPaymentsBody.innerHTML=data.teacherPayments.slice().reverse().map(p=>`<tr><td>${esc(p.month)}</td><td>${esc(getTeacherName(p.teacherId))}</td><td>${p.type==='heure'?'Heure fournie':'Plein temps'}</td><td>${money(p.amount)}</td><td>${p.paidDate}</td><td>${esc(p.receiptNumber)}</td><td><button class="btn mini" data-print-tpay="${p.id}">Imprimer</button></td></tr>`).join('')||'<tr><td colspan="7">Aucun paiement de professeur.</td></tr>';
document.querySelectorAll('[data-print-tpay]').forEach(b=>b.onclick=()=>printTeacherReceipt(b.dataset.printTpay))}
function payTeacher(id){const t=data.teachers.find(x=>x.id===id);if(!t)return;const month=teacherMonth.value||currentMonth();const already=data.teacherPayments.some(p=>p.teacherId===id&&p.month===month);if(already&&!confirm('Ce professeur a déjà un paiement enregistré pour ce mois. Ajouter un autre paiement ?'))return;const amount=teacherPay(t);if(amount<=0)return toast('Le montant calculé est de 0 HTG. Vérifiez les données du professeur.');const rn=teacherReceipt(data.meta.nextTeacherReceipt++);data.teacherPayments.push({id:uid(),teacherId:id,month,type:t.type,amount,paidDate:today(),receiptNumber:rn,hoursWorked:t.hoursWorked,hoursAbsent:t.hoursAbsent,daysAbsent:t.daysAbsent,dress:t.dress});save();toast('Paiement professeur enregistré — '+rn)}
function printTeacherReceipt(id){const p=data.teacherPayments.find(x=>x.id===id);if(!p)return;const w=window.open('','_blank','width=800,height=900');w.document.write(`<html><head><title>${esc(p.receiptNumber)}</title><style>body{font-family:Arial;padding:30px}.receipt{max-width:680px;margin:auto;border:2px solid #176b52;padding:28px}.head{display:flex;justify-content:space-between}.box{margin:25px 0;padding:18px;background:#f1f6f3;font-size:20px}.sign{display:flex;justify-content:space-between;margin-top:70px}</style></head><body><div class="receipt"><div class="head"><div><h2>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h2><p>REÇU DE PAIEMENT DU PROFESSEUR</p></div><strong>${esc(p.receiptNumber)}</strong></div><hr><p><b>Professeur :</b> ${esc(getTeacherName(p.teacherId))}</p><p><b>Mois :</b> ${esc(p.month)}</p><p><b>Type :</b> ${p.type==='heure'?'Heure fournie':'Plein temps'}</p><p><b>Heures travaillées :</b> ${p.hoursWorked||0}</p><p><b>Absences :</b> ${p.hoursAbsent||0} h / ${p.daysAbsent||0} j</p><p><b>Tenue :</b> ${esc(p.dress||'—')}</p><div class="box">Montant payé : <strong>${money(p.amount)}</strong></div><div class="sign"><span>Signature professeur</span><span>Signature IMDS</span></div></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function renderMonthlyReport(){const month=reportMonth.value||currentMonth();const pays=data.payments.filter(p=>p.date.startsWith(month));const tp=data.teacherPayments.filter(p=>p.month===month);const revenue=pays.reduce((a,p)=>a+Number(p.amount||0),0),payroll=tp.reduce((a,p)=>a+Number(p.amount||0),0);reportStudentRevenue.textContent=money(revenue);reportTeacherPayroll.textContent=money(payroll);reportNet.textContent=money(revenue-payroll);reportPaymentCount.textContent=pays.length;const modes={};pays.forEach(p=>{modes[p.mode]??={count:0,total:0};modes[p.mode].count++;modes[p.mode].total+=Number(p.amount||0)});reportModesBody.innerHTML=Object.entries(modes).map(([m,v])=>`<tr><td>${esc(m)}</td><td>${v.count}</td><td>${money(v.total)}</td></tr>`).join('')||'<tr><td colspan="3">Aucune recette.</td></tr>';reportPaymentsBody.innerHTML=pays.map(p=>`<tr><td>${p.date}</td><td>${esc(p.receiptNumber)}</td><td>${esc(studentName(p.studentId))}</td><td>${esc(p.reason)}</td><td>${esc(p.mode)}</td><td>${money(p.amount)}</td></tr>`).join('')||'<tr><td colspan="6">Aucune recette.</td></tr>';reportTeachersBody.innerHTML=tp.map(p=>`<tr><td>${esc(getTeacherName(p.teacherId))}</td><td>${esc(p.month)}</td><td>${p.type==='heure'?'Heure fournie':'Plein temps'}</td><td>${money(p.amount)}</td><td>${p.paidDate}</td><td>${esc(p.receiptNumber)}</td></tr>`).join('')||'<tr><td colspan="6">Aucun paiement professeur.</td></tr>'}
function printMonthly(){const month=reportMonth.value||currentMonth();renderMonthlyReport();const w=window.open('','_blank','width=900,height=1000');w.document.write(`<html><head><title>Rapport financier ${month}</title><style>body{font-family:Arial;padding:25px}.head{text-align:center;border-bottom:2px solid #176b52;padding-bottom:12px}.cards{display:flex;gap:10px;margin:18px 0}.card{flex:1;border:1px solid #ddd;padding:12px}.card b{display:block;font-size:18px;margin-top:5px}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #ddd;padding:7px;text-align:left}th{background:#f1f5f3}.section{margin-top:25px}.sign{display:flex;justify-content:space-between;margin-top:60px}</style></head><body><div class="head"><h1>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h1><h2>RAPPORT FINANCIER MENSUEL</h2><p>Mois : ${month}</p></div><div class="cards"><div class="card">Recettes élèves<b>${reportStudentRevenue.textContent}</b></div><div class="card">Paiements professeurs<b>${reportTeacherPayroll.textContent}</b></div><div class="card">Solde mensuel<b>${reportNet.textContent}</b></div></div><div class="section"><h3>Recettes par mode</h3>${reportModesBody.parentElement.outerHTML}</div><div class="section"><h3>Détail des recettes</h3>${reportPaymentsBody.parentElement.outerHTML}</div><div class="section"><h3>Paiements des professeurs</h3>${reportTeachersBody.parentElement.outerHTML}</div><div class="sign"><span>Préparé par : __________________</span><span>Direction : __________________</span></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function renderAll(){renderStudents();fillSelects();renderPayments();renderFinance();renderGrades();renderAttendance();renderSocial();renderReceiptPreview();renderTeachers();renderMonthlyReport()}
initDepartments();renderAll();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));
