const KEY='imds_school_manager_v3';
const defaultData={students:[],payments:[],grades:[],attendance:[],social:[],meta:{nextReceipt:1}};
let data=loadData();
const departments={
'Ouest':['Port-au-Prince','Delmas','Pétion-Ville','Kenscoff','Carrefour','Gressier','Léogâne','Grand-Goâve','Petit-Goâve','Fonds-Verrettes','Cornillon','Thomazeau','Ganthier','Croix-des-Bouquets','Cité Soleil','Tabarre','Cabaret','Arcahaie','Anse-à-Galets','Pointe-à-Raquette'],
'Sud-Est':['Jacmel','Cayes-Jacmel','La Vallée-de-Jacmel','Marigot','Bainet','Côtes-de-Fer','Belle-Anse','Anse-à-Pitres','Thiotte','Grand-Gosier'],
'Nord':['Cap-Haïtien','Limonade','Quartier-Morin','Acul-du-Nord','Plaine-du-Nord','Milot','Grande-Rivière-du-Nord','Dondon','Saint-Raphaël','Pignon','La Victoire','Ranquitte','Borgne','Port-Margot','Limbé','Bas-Limbé','Plaisance','Pilate','Bahon'],
'Nord-Est':['Fort-Liberté','Ferrier','Perches','Ouanaminthe','Capotille','Mont-Organisé','Trou-du-Nord','Caracol','Sainte-Suzanne','Terrier-Rouge','Vallières','Carice','Mombin-Crochu'],
'Artibonite':['Gonaïves','Ennery','L’Estère','Gros-Morne','Terre-Neuve','Anse-Rouge','Saint-Marc','Verrettes','La Chapelle','Dessalines','Desdunes','Grande-Saline','Petite-Rivière-de-l’Artibonite','Marmelade','Saint-Michel-de-l’Attalaye','Liancourt','Montrouis'],
'Centre':['Hinche','Cerca-la-Source','Cerca-Carvajal','Maïssade','Thomonde','Thomassique','Mirebalais','Saut-d’Eau','Boucan-Carré','Lascahobas','Belladère','Savanette','Baptiste'],
'Sud':['Les Cayes','Torbeck','Chantal','Camp-Perrin','Maniche','Île-à-Vache','Port-Salut','Saint-Jean-du-Sud','Arniquet','Aquin','Saint-Louis-du-Sud','Cavaillon','Les Côteaux','Port-à-Piment','Roche-à-Bateau','Chardonnières','Les Anglais','Tiburon'],
'Grande-Anse':['Jérémie','Abricots','Bonbon','Chambellan','Moron','Marfranc','Anse-d’Hainault','Dame-Marie','Les Irois','Corail','Beaumont','Pestel','Roseaux'],
'Nord-Ouest':['Môle-Saint-Nicolas','Baie-de-Henne','Bombardopolis','Jean-Rabel','Port-de-Paix','Bassin-Bleu','Chansolme','La Tortue','La Pointe des Palmistes','Saint-Louis-du-Nord','Anse-à-Foleur'],
'Nippes':['Miragoâne','Petite-Rivière-de-Nippes','Fonds-des-Nègres','Paillant','Anse-à-Veau','Petit-Trou-de-Nippes','L’Asile','Arnaud','Baradères','Grand-Boucan','Plaisance-du-Sud']};
function loadData(){try{const d=JSON.parse(localStorage.getItem(KEY));return d&&d.students&&d.payments?Object.assign(structuredClone(defaultData),d):structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function money(n){return new Intl.NumberFormat('fr-FR').format(Number(n)||0)+' HTG'}
function today(){return new Date().toLocaleDateString('fr-CA')}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function studentName(id){const s=data.students.find(x=>x.id===id);return s?s.fullName:'Élève supprimé'}
function paidFor(id){return data.payments.filter(p=>p.studentId===id).reduce((a,p)=>a+Number(p.amount||0),0)}
function dueFor(s){return Number(s.annualRequested||0)+Number(s.previousBalance||0)}
function tariffAmount(type){return Number({normal:normalPrice.value,bourse:scholarshipPrice.value,demi:halfScholarshipPrice.value,special:specialPrice.value}[type]||0)}
function showSection(id){document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.section===id));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showSection(b.dataset.section));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showSection(b.dataset.go));
function initDepartments(){birthDepartment.innerHTML='<option value="">Choisir le département</option>'+Object.keys(departments).map(d=>`<option>${esc(d)}</option>`).join('')}
birthDepartment.onchange=()=>{const list=departments[birthDepartment.value]||[];birthCommune.disabled=!list.length;birthCommune.innerHTML='<option value="">Choisir la commune</option>'+list.map(c=>`<option>${esc(c)}</option>`).join('')}
tariffType.onchange=()=>{annualRequested.value=tariffAmount(tariffType.value)};[normalPrice,scholarshipPrice,halfScholarshipPrice,specialPrice].forEach(x=>x.oninput=()=>{if(tariffType.value)annualRequested.value=tariffAmount(tariffType.value)});
studentPhoto.onchange=()=>{const f=studentPhoto.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas'),max=360,scale=Math.min(1,max/Math.max(im.width,im.height));c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);photoPreview.src=c.toDataURL('image/jpeg',.78);photoPreview.classList.remove('hidden')};im.src=r.result};r.readAsDataURL(f)};
function renderStudents(){const q=studentSearch.value.toLowerCase();const rows=data.students.filter(s=>[s.fullName,s.nisu,s.class].join(' ').toLowerCase().includes(q)).map(s=>{const p=paidFor(s.id),d=dueFor(s);return `<tr><td>${s.photo?`<img class="avatar" src="${s.photo}" alt="">`:''}${esc(s.fullName)}</td><td>${esc(s.nisu||'—')}</td><td>${esc(s.class)}</td><td>${esc(s.tariffType||'—')}</td><td>${money(d)}</td><td>${money(p)}</td><td>${money(Math.max(0,d-p))}</td><td><span class="status ${s.status}">${esc(s.status)}</span></td><td><button class="btn mini" data-edit="${s.id}">Modifier</button> <button class="btn mini danger" data-delete="${s.id}">Supprimer</button></td></tr>`}).join('');studentsBody.innerHTML=rows||'<tr><td colspan="9">Aucun élève enregistré.</td></tr>';
document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cet élève et tout son historique ?')){const id=b.dataset.delete;data.students=data.students.filter(s=>s.id!==id);data.payments=data.payments.filter(p=>p.studentId!==id);data.grades=data.grades.filter(g=>g.studentId!==id);data.attendance=data.attendance.filter(a=>a.studentId!==id);save();toast('Élève supprimé')}});
document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editStudent(b.dataset.edit))}
function editStudent(id){const s=data.students.find(x=>x.id===id);if(!s)return;Object.entries({nisu:s.nisu,lastName:s.lastName,firstName:s.firstName,birthDate:s.birthDate,sex:s.sex,birthPlace:s.birthPlace,address:s.address,motherName:s.motherName,fatherName:s.fatherName,guardianName:s.guardianName,guardianPhone:s.guardianPhone,guardianCIN:s.guardianCIN,referredBy:s.referredBy,normalPrice:s.normalPrice,scholarshipPrice:s.scholarshipPrice,halfScholarshipPrice:s.halfScholarshipPrice,specialPrice:s.specialPrice,tariffType:s.tariffType,annualRequested:s.annualRequested,previousBalance:s.previousBalance,studentStatus:s.status}).forEach(([id,v])=>{if(document.getElementById(id))document.getElementById(id).value=v??''});studentClass.value=s.class;birthDepartment.value=s.birthDepartment||'';birthDepartment.onchange();birthCommune.value=s.birthCommune||'';photoPreview.src=s.photo||'';photoPreview.classList.toggle('hidden',!s.photo);studentForm.dataset.edit=id;showSection('students');window.scrollTo({top:0,behavior:'smooth'});toast('Mode modification activé')}
function fillSelects(){const o=data.students.map(s=>`<option value="${s.id}">${esc(s.fullName)} — ${esc(s.class)}</option>`).join('')||'<option value="">Aucun élève</option>';['paymentStudent','gradeStudent','attendanceStudent'].forEach(id=>document.getElementById(id).innerHTML=o);receiptSelect.innerHTML=data.payments.slice().reverse().map(p=>`<option value="${p.id}">${esc(p.receiptNumber)} — ${esc(studentName(p.studentId))} — ${money(p.amount)}</option>`).join('')||'<option value="">Aucun paiement</option>'}
function renderPayments(){paymentsBody.innerHTML=data.payments.slice().reverse().map(p=>`<tr><td>${p.date}</td><td>${esc(p.receiptNumber)}</td><td>${esc(studentName(p.studentId))}</td><td>${esc(p.reason)}</td><td>${esc(p.mode)}</td><td>${money(p.amount)}</td><td><button class="btn mini" data-receipt="${p.id}">Reçu</button></td></tr>`).join('')||'<tr><td colspan="7">Aucun paiement.</td></tr>';document.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>{showSection('receipts');receiptSelect.value=b.dataset.receipt;renderReceiptPreview()})}
function renderFinance(){let due=0,paid=0,up=0,late=0;const rows=data.students.map(s=>{const d=dueFor(s),p=paidFor(s),bal=Math.max(0,d-p);due+=d;paid+=p;if(bal<=0)up++;else late++;return `<tr><td>${esc(s.fullName)}</td><td>${money(s.annualRequested)}</td><td>${money(s.previousBalance)}</td><td>${money(d)}</td><td>${money(p)}</td><td>${money(bal)}</td><td>${bal<=0?'À jour':'En retard'}</td></tr>`}).join('');financeBody.innerHTML=rows||'<tr><td colspan="7">Aucun élève.</td></tr>';financeDue.textContent=money(due);financePaid.textContent=money(paid);financeBalance.textContent=money(Math.max(0,due-paid));financeUp.textContent=up;financeLate.textContent=late;statStudents.textContent=data.students.length;statAnnual.textContent=money(paid);statBalance.textContent=money(Math.max(0,due-paid));statUpToDate.textContent=up;statLate.textContent=late;const ym=today().slice(0,7);statToday.textContent=money(data.payments.filter(p=>p.date===today()).reduce((a,p)=>a+Number(p.amount),0));statMonth.textContent=money(data.payments.filter(p=>p.date.startsWith(ym)).reduce((a,p)=>a+Number(p.amount),0))}
function renderGrades(){gradesBody.innerHTML=data.grades.slice().reverse().map(g=>`<tr><td>${esc(studentName(g.studentId))}</td><td>${esc(g.subject)}</td><td>${g.value}/100</td><td>${g.date}</td></tr>`).join('')||'<tr><td colspan="4">Aucune note.</td></tr>'}
function renderAttendance(){attendanceBody.innerHTML=data.attendance.slice().reverse().slice(0,100).map(a=>`<tr><td>${a.date}</td><td>${esc(studentName(a.studentId))}</td><td>${esc(a.status)}</td></tr>`).join('')||'<tr><td colspan="3">Aucune présence.</td></tr>';statAttendance.textContent=data.attendance.filter(a=>a.date===today()).length}
function renderSocial(){socialFeed.innerHTML=data.social.slice().reverse().map(p=>`<div class="social-post panel"><div><strong>${esc(p.author)}</strong><span>${p.date}</span></div><p>${esc(p.message)}</p></div>`).join('')||'<div class="panel">Aucune publication.</div>'}
function receiptHtml(p){const s=data.students.find(x=>x.id===p.studentId);return `<div class="receipt"><div class="receipt-head"><div><h2>INSTITUTION MIXTE LE DOMAINE DU SAVOIR</h2><p>REÇU DE PAIEMENT</p></div><strong>${esc(p.receiptNumber)}</strong></div><hr><p><b>Élève :</b> ${esc(s?.fullName||'')}</p><p><b>NISU :</b> ${esc(s?.nisu||'—')} &nbsp; <b>Classe :</b> ${esc(s?.class||'')}</p><p><b>Date :</b> ${p.date}</p><p><b>Motif :</b> ${esc(p.reason)}</p><p><b>Mode :</b> ${esc(p.mode)}</p><div class="amount-box">Montant payé : <strong>${money(p.amount)}</strong></div><p class="small">Merci pour votre paiement.</p><div class="signatures"><span>Signature responsable</span><span>Cachet / Signature IMDS</span></div></div>`}
function renderReceiptPreview(){const p=data.payments.find(x=>x.id===receiptSelect.value);receiptPreview.innerHTML=p?receiptHtml(p):'<p>Aucun paiement sélectionné.</p>'}
studentForm.onsubmit=e=>{e.preventDefault();const id=studentForm.dataset.edit||uid();const photo=photoPreview.src&&!photoPreview.classList.contains('hidden')?photoPreview.src:'';const obj={id,nisu:nisu.value.trim(),lastName:lastName.value.trim(),firstName:firstName.value.trim(),fullName:(lastName.value.trim()+' '+firstName.value.trim()).trim(),class:studentClass.value,birthDate:birthDate.value,sex:sex.value,birthPlace:birthPlace.value.trim(),birthDepartment:birthDepartment.value,birthCommune:birthCommune.value,address:address.value.trim(),motherName:motherName.value.trim(),fatherName:fatherName.value.trim(),guardianName:guardianName.value.trim(),guardianPhone:guardianPhone.value.trim(),guardianCIN:guardianCIN.value.trim(),referredBy:referredBy.value.trim(),normalPrice:Number(normalPrice.value)||0,scholarshipPrice:Number(scholarshipPrice.value)||0,halfScholarshipPrice:Number(halfScholarshipPrice.value)||0,specialPrice:Number(specialPrice.value)||0,tariffType:tariffType.value,annualRequested:Number(annualRequested.value)||0,previousBalance:Number(previousBalance.value)||0,status:studentStatus.value,photo:photo||(data.students.find(s=>s.id===id)?.photo||'')};const i=data.students.findIndex(s=>s.id===id);if(i>=0)data.students[i]=obj;else data.students.push(obj);delete studentForm.dataset.edit;studentForm.reset();annualRequested.value=0;photoPreview.src='';photoPreview.classList.add('hidden');save();toast(i>=0?'Dossier modifié':'Élève enregistré')};
resetStudentBtn.onclick=()=>{delete studentForm.dataset.edit;setTimeout(()=>{photoPreview.src='';photoPreview.classList.add('hidden')},0)};
studentSearch.oninput=renderStudents;
paymentForm.onsubmit=e=>{e.preventDefault();const sid=paymentStudent.value;if(!sid)return toast('Ajoutez d’abord un élève');const rn=receiptNumber.value.trim()||`IMDS-${String(data.meta.nextReceipt++).padStart(6,'0')}`;data.payments.push({id:uid(),studentId:sid,amount:Number(paymentAmount.value),reason:paymentReason.value,mode:paymentMode.value,receiptNumber:rn,note:paymentNote.value.trim(),date:today()});paymentForm.reset();save();toast('Paiement enregistré — reçu '+rn);showSection('receipts');receiptSelect.value=data.payments[data.payments.length-1].id;renderReceiptPreview()};
gradeForm.onsubmit=e=>{e.preventDefault();data.grades.push({id:uid(),studentId:gradeStudent.value,subject:gradeSubject.value.trim(),value:Number(gradeValue.value),date:today()});e.target.reset();save();toast('Note enregistrée')};attendanceForm.onsubmit=e=>{e.preventDefault();data.attendance.push({id:uid(),studentId:attendanceStudent.value,status:attendanceStatus.value,date:today()});save();toast('Présence enregistrée')};
socialForm.onsubmit=e=>{e.preventDefault();data.social.push({id:uid(),author:socialAuthor.value.trim(),message:socialMessage.value.trim(),date:new Date().toLocaleString('fr-FR')});e.target.reset();save();toast('Publication ajoutée')};
receiptSelect.onchange=renderReceiptPreview;previewReceiptBtn.onclick=renderReceiptPreview;printReceiptBtn.onclick=()=>{const p=data.payments.find(x=>x.id===receiptSelect.value);if(!p)return;const w=window.open('','_blank','width=800,height=900');w.document.write(`<html><head><title>${esc(p.receiptNumber)}</title><style>body{font-family:Arial;padding:30px}.receipt{max-width:680px;margin:auto;border:2px solid #176b52;padding:28px}.receipt-head{display:flex;justify-content:space-between;gap:20px}.receipt-head h2{font-size:20px}.amount-box{margin:25px 0;padding:18px;background:#f1f6f3;font-size:20px}.signatures{display:flex;justify-content:space-between;margin-top:70px}.small{color:#666}</style></head><body>${receiptHtml(p)}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()};
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`IMDS-sauvegarde-${today()}.json`;a.click();URL.revokeObjectURL(a.href);securityMessage.textContent='Sauvegarde exportée.'};
importFile.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.students||!x.payments)throw Error();data=Object.assign(structuredClone(defaultData),x);save();toast('Sauvegarde importée')}catch{alert('Fichier de sauvegarde invalide.')}};r.readAsText(f)};
clearBtn.onclick=()=>{if(confirm('ATTENTION : effacer toutes les données locales de l’IMDS sur cet appareil ?')){data=structuredClone(defaultData);save();toast('Données effacées')}};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden')});installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add('hidden')}};
function renderAll(){renderStudents();fillSelects();renderPayments();renderFinance();renderGrades();renderAttendance();renderSocial();renderReceiptPreview()}
initDepartments();renderAll();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));
